'use client';
import { useState } from 'react';
import { defaultRunSpec, parseRunSpec, type RunSpec } from './run-spec';
import { fuseCatalog } from './engine-catalog';
import { downloadJson } from './SimulationPanels';
export default function EngineWorkspace({en}:{en:boolean}) {
  const [spec,setSpec]=useState(defaultRunSpec); const [domain,setDomain]=useState('all'); const [notice,setNotice]=useState('');
  let valid=true;try{parseRunSpec(spec);}catch{valid=false;}
  const setSolver=(key:keyof RunSpec['solver'],n:number)=>setSpec(s=>({...s,solver:{...s.solver,[key]:n}}));
  return <div className="simEngineWorkspace">
    <section className="simPanel"><div className="simPanelTitle"><div><p className="simMiniLabel">ENGINE WORKFLOW / FUSE 1.2.0</p><h3>{en?'Reproducible DIII-D execution':'可复现的 DIII-D 计算'}</h3></div><span className="simWarning">{en?'Local executor · public replay only':'本地执行 · 公网只读回放'}</span></div><p>{en?'Export a validated RunSpec and run it with the independent local supervisor. The selected recipe, model, solver limits and resources are applied to Julia; no arbitrary command or device-data fetching is accepted.':'导出经过校验的 RunSpec，由独立本地执行器运行。所选流程、模型、求解参数和资源限制会实际映射到 Julia；不接受任意命令或装置数据拉取。'}</p>
    <div className="simRecipeForm"><label>{en?'Workflow':'计算流程'}<select value={spec.recipe} onChange={e=>setSpec(s=>({...s,recipe:e.target.value as RunSpec['recipe'],model:'TGLFNN'}))}><option value="diiid-lmode-fluxmatch">DIII-D L-mode · {en?'fixed-equilibrium flux matching':'固定平衡输运匹配'}</option><option value="diiid-default-stationary">DIII-D default · {en?'coupled stationary plasma':'耦合稳态等离子体'}</option></select></label><label>{en?'Transport model':'输运模型'}<select value={spec.model} onChange={e=>setSpec(s=>({...s,model:e.target.value as RunSpec['model']}))}>{(spec.recipe==='diiid-default-stationary'?['TGLFNN']:['TGLFNN','GKNN','QLNN']).map(m=><option key={m}>{m}</option>)}</select></label>
    <label>{en?'Solver max iterations':'内层最大迭代'}<input type="number" min={1} max={300} value={spec.solver.maxIterations} onChange={e=>setSolver('maxIterations',e.target.valueAsNumber)}/></label><label>xtol · {en?'step tolerance':'步长容差'}<input type="number" min={0.00001} max={0.01} step={0.0001} value={spec.solver.xtol} onChange={e=>setSolver('xtol',e.target.valueAsNumber)}/></label>
    {spec.recipe==='diiid-default-stationary'&&<><label>{en?'Outer max iterations':'外层最大迭代'}<input type="number" min={2} max={10} value={spec.solver.stationaryIterations} onChange={e=>setSolver('stationaryIterations',e.target.valueAsNumber)}/></label><label>{en?'Outer profile-change threshold':'外层剖面变化阈值'}<input type="number" min={0.001} max={0.1} step={0.001} value={spec.solver.stationaryThreshold} onChange={e=>setSolver('stationaryThreshold',e.target.valueAsNumber)}/></label></>}
    <label>{en?'CPU threads':'CPU 线程'}<input type="number" min={1} max={8} value={spec.resources.threads} onChange={e=>setSpec(s=>({...s,resources:{...s.resources,threads:e.target.valueAsNumber}}))}/></label><label>{en?'Timeout / s':'超时 / 秒'}<input type="number" min={60} max={7200} value={spec.resources.timeoutSeconds} onChange={e=>setSpec(s=>({...s,resources:{...s.resources,timeoutSeconds:e.target.valueAsNumber}}))}/></label></div>
    {!valid&&<p role="alert" className="simWarning">{en?'Enter values within the supported bounds.':'请将参数填写为支持范围内的数值。'}</p>}<button className="simButton simButtonPrimary" disabled={!valid} onClick={()=>{downloadJson(parseRunSpec(spec),'fuse-run-spec.json');setNotice(en?'RunSpec exported; no computation has started in this browser.':'已导出计算规格；本浏览器未启动计算。');}}>{en?'Export executable RunSpec':'导出可执行 RunSpec'} ↓</button><p role="status">{notice}</p>
    <ol className="simExecutionSteps"><li>{en?'Export specification':'导出规格'} <code>simulation-runspec.v1</code></li><li>{en?'Local supervised execution':'本地受控运行'} <code>npm run simulation:run -- run --spec fuse-run-spec.json</code></li><li>{en?'Inspect / cancel / collect':'查看状态 / 取消 / 核验制品'} <code>status / cancel --run-id &lt;id&gt;</code></li><li>{en?'Review and publish safe results':'审核并发布安全结果投影'} <code>simulation:publish-diiid</code></li></ol><p className="simChartNote">{en?'One attempt at a time. Retry creates a new immutable attempt; it never overwrites scientific evidence. Native HDF5 and model weights stay local. No public queue is connected. Docker/HPC backends must use a separate authenticated gateway.':'每次一个任务。重试产生新的不可变 Attempt，不覆盖科学证据；原生 HDF5 与模型权重留在本地。当前未连接公网任务队列；Docker/HPC 后端需独立鉴权网关。'}</p></section>
    <section className="simPanel"><div className="simPanelTitle"><div><p className="simMiniLabel">CAPABILITY INVENTORY</p><h3>{en?'FUSE functional coverage map':'FUSE 完整功能覆盖地图'}</h3></div><span>71 {en?'Actor types · 18 families':'个 Actor 类型 · 18 个家族'}</span></div><p>{en?'This is the complete actor-type inventory of the pinned source, not 71 verified solvers. A recipe passing does not qualify every model in its family. Source presence, execution, convergence and device validation are separate.':'这里是固定源码的完整 Actor 类型清单，不是 71 个已验证求解器。单个算例通过不代表所属家族全部模型通过；源码存在、执行成功、数值收敛和装置验证分别管理。'}</p><div className="simChartControls"><label>{en?'Domain':'领域'}<select value={domain} onChange={e=>setDomain(e.target.value)}><option value="all">{en?'All':'全部'}</option><option value="physics">01 · {en?'Physics':'物理模拟'}</option><option value="engineering">02 · {en?'Engineering':'工程设计'}</option><option value="shared">{en?'Shared orchestration':'共用编排'}</option></select></label><span>{en?'Runtime coverage: recipe-specific; no device qualification':'运行覆盖按具体流程核验；装置验证尚未建立'}</span></div><div className="simCapabilityGrid">{fuseCatalog.families.filter(f=>domain==='all'||f.domain===domain).map(f=><details key={f.id}><summary><span>{en?f.en:f.zh}</span><small>{f.actors.length} Actor</small></summary><p className="simChartNote">{en?f.note:'源码已登记；模型与依赖需独立验证，不能继承其他算例资格。'}</p><ul>{f.actors.map(a=><li key={a}><code>{a}</code></li>)}</ul></details>)}</div><p className="simChartNote">{en?'Engineering validation requires FPP/ITER cases; external CHEASE, GACODE/QLGYRO/NEO, RABBIT/TORBEAM/MARS and optional model bundles need separate runtime and license checks.':'工程验证需要 FPP/ITER 等补充算例；外部 CHEASE、GACODE/QLGYRO/NEO、RABBIT/TORBEAM/MARS 及可选模型包需分别核验运行环境与许可证。'}</p></section>
  </div>;
}
