'use client';
import { useEffect, useState } from 'react';
import ScientificChart from '../components/charts/ScientificChart';
import { useChartTheme } from '../components/charts/chart-theme';
import bundles from './data/engineering-bundles.json';
import { loadEngineering, type EngineeringBundle, type EngineeringData, type MagneticMetric } from './engineering';
import type { SimulationRun } from './contract';
import { downloadJson } from './SimulationPanels';

const metricNames: Record<string, [string, string]> = { rampup_flux: ['升流磁通', 'Ramp-up flux'], flattop_flux: ['平顶磁通', 'Flat-top flux'], pf_flux: ['PF 磁通', 'PF flux'], flattop_duration: ['最大平顶能力', 'Maximum flat-top capability'], oh_current_density: ['OH 电流密度', 'OH current density'], oh_field: ['OH 磁场', 'OH field'], tf_current_density: ['TF 电流密度', 'TF current density'], tf_field: ['TF 磁场', 'TF field'] };
const statusNames = { missing: ['缺失', 'Missing'], nan: ['未定义', 'Undefined'], 'positive-infinity': ['+∞（无有限值）', '+∞ (not finite)'], 'negative-infinity': ['−∞（无有限值）', '−∞ (not finite)'] } as const;
const displayMetric = (m: MagneticMetric, en: boolean) => m.status === 'finite' ? m.value!.toPrecision(6) : statusNames[m.status][en ? 1 : 0];
export default function EngineeringResults({ run, en, trusted }: { run: SimulationRun; en: boolean; trusted: boolean }) {
  const theme = useChartTheme();
  const bundle = trusted ? (bundles as EngineeringBundle[]).find(b => b.parentRunId === run.id && b.parentRecordSha256 === run.source.recordSha256) : undefined;
  const [state, setState] = useState<{ key: string; data?: EngineeringData; error?: boolean }>({ key: '' });
  const [retry, setRetry] = useState(0); const [sampling, setSampling] = useState(401); const [table, setTable] = useState(false);
  useEffect(() => { const c = new AbortController(); if (bundle) void loadEngineering(bundle, c.signal).then(data => { if (!c.signal.aborted) setState({ key: bundle.runId, data }); }).catch(() => { if (!c.signal.aborted) setState({ key: bundle.runId, error: true }); }); return () => c.abort(); }, [bundle, retry]);
  if (!bundle) return <p className="simScienceBoundary">{en ? 'No linked structural-response run is available for this case. Geometry is not a stress result.' : '此算例没有已关联的结构响应运行；几何展示不等于应力结果。'}</p>;
  const data = state.key === bundle.runId ? state.data : undefined;
  if (!data) return <section className="simPanel" role="status"><h3>{state.error ? (en ? 'Engineering result verification failed' : '工程结果校验失败') : (en ? 'Verifying engineering results…' : '正在校验工程结果…')}</h3>{state.error && <button className="simButton" onClick={() => setRetry(v => v + 1)}>{en ? 'Retry' : '重试'}</button>}</section>;
  const branch = data.branches.find(b => b.samplingPoints === sampling)!;
  const option = (unit: string, series: unknown[]) => ({ color: theme.mode === 'dark' ? ['#81b7ba', '#e7a182', '#c6b9ed'] : ['#327b80', '#aa694b', '#7776a6'], animation: false, legend: { top: 5 }, tooltip: { trigger: 'axis' }, grid: { left: 72, right: 25, top: 55, bottom: 48 }, xAxis: { type: 'value', name: 'R / m', nameLocation: 'middle', nameGap: 28, scale: true }, yAxis: { type: 'value', name: unit, scale: true }, dataZoom: [{ type: 'inside', filterMode: 'none' }], series });
  return <>
    <section className="simPanel simTransport"><div className="simPanelTitle"><div><p className="simMiniLabel">ENGINEERING / DERIVED RUN</p><h3>{en ? 'Magnetic capability & center-stack mechanics' : '磁体能力与中心柱力学'}</h3></div><button className="simButton" onClick={() => downloadJson(data, `${data.runId}.json`)}>JSON ↓</button></div>
      <p className="simScienceBoundary">{en ? 'SIMULATED · 1D analytical cylindrical model, not 3D finite elements. Fixed FPP geometry; OH at configured current margin. No material allowable-stress or device qualification.' : 'SIMULATED · 1D 解析圆柱模型，非三维有限元。固定 FPP 几何，OH 使用配置的电流裕量；未进行材料许用应力或装置资格验证。'}</p>
      <p className="simNotice">{en ? 'Computed peak equivalent stresses are approximately 1.21 GPa (TF) and 1.75 GPa (OH). Material properties and allowable stresses require independent assessment; successful execution does not establish structural safety.' : '本算例等效应力峰值约为 TF 1.21 GPa、OH 1.75 GPa。需要独立核验材料与许用应力；执行成功不代表结构安全。'}</p>
      <p className="simVariablePath"><code>{data.runId}</code><span>{en ? 'Derived from' : '派生自'} {data.parentRunId} · t = {data.timeSeconds} s · SHA-256</span></p>
      <div className="simDataScroll"><table className="simTable"><thead><tr><th>{en ? 'Quantity' : '物理量'}</th><th>{en ? 'Value' : '数值'}</th><th>{en ? 'Unit' : '单位'}</th></tr></thead><tbody>{Object.entries(data.metrics).map(([id, m]) => <tr key={id}><td>{metricNames[id][en ? 1 : 0]}</td><td>{displayMetric(m, en)}</td><td>{m.unit}</td></tr>)}</tbody></table></div>
      <p className="simChartNote">{en ? 'Capability calculation, not a prescribed pulse. Missing and nonfinite values remain explicit; a negative duration indicates an infeasible capability, not zero.' : '此处计算最大平顶能力，不是指定脉冲。缺失和非有限值显式展示；若持续时间为负，表示该能力不可行，不置零。'}</p>
    </section>
    <section className="simPanel simTransport"><div className="simPanelTitle"><h3>{en ? 'Resolved stress & displacement' : '应力与位移剖面'}</h3><div className="simFieldTools"><label>{en ? 'Analytical samples' : '解析采样点数'}<select value={sampling} onChange={e => setSampling(Number(e.target.value))}>{data.branches.map(b => <option key={b.samplingPoints}>{b.samplingPoints}</option>)}</select></label><button className="simButton" aria-pressed={table} onClick={() => setTable(v => !v)}>{table ? (en ? 'Show charts' : '显示曲线') : (en ? 'Exact samples' : '精确采样值')}</button></div></div>
      <div className="simTransportGrid simFluxGrid">{branch.parts.map(p => <div key={p.id}><h4>{p.id.toUpperCase()} · {en ? 'axial stress' : '轴向应力'} {(p.axialPa / 1e6).toPrecision(6)} MPa</h4>{table ? <div className="simDataScroll"><table className="simTable"><thead><tr><th>R / m</th><th>σr / Pa</th><th>σθ / Pa</th><th>σVM / Pa</th><th>u / m</th></tr></thead><tbody>{p.r.map((r, i) => <tr key={i}><td>{r}</td><td>{p.radialPa[i]}</td><td>{p.hoopPa[i]}</td><td>{p.vonMisesPa[i]}</td><td>{p.displacementM[i]}</td></tr>)}</tbody></table></div> : <><ScientificChart key={`stress-${sampling}-${p.id}`} id={`stress-${data.runId}-${p.id}`} eager height={295} ariaLabel={`${p.id} analytical stresses MPa`} fallbackSrc="" fallbackAlt="" fallback={<p>{en ? 'Use exact samples.' : '可切换精确采样值。'}</p>} option={option('MPa', ([['radialPa', 'σr'], ['hoopPa', 'σθ'], ['vonMisesPa', 'σVM']] as const).map(([key, name]) => ({ name, type: 'line', showSymbol: false, smooth: false, data: p.r.map((r, i) => [r, p[key][i] / 1e6]) })))}/><ScientificChart key={`displacement-${sampling}-${p.id}`} id={`displacement-${data.runId}-${p.id}`} eager height={240} ariaLabel={`${p.id} radial displacement mm`} fallbackSrc="" fallbackAlt="" fallback={<p>{en ? 'Use exact samples.' : '可切换精确采样值。'}</p>} option={option('mm', [{ name: en ? 'Radial displacement' : '径向位移', type: 'line', showSymbol: false, smooth: false, data: p.r.map((r, i) => [r, p.displacementM[i] * 1000]) }])}/></>}</div>)}</div>
      <p className="simChartNote">{en ? 'Stress sign is preserved. OH on/off state is selected by the peak for each component, not a pointwise envelope. Wheel/pinch zoom; changing sample count resets the chart.' : '应力保留正负号。OH 通断状态按每个部件的峰值选取，不是逐点包络。支持滚轮/双指缩放；更换采样点数可重置视图。'}</p>
    </section>
    <section className="simPanel simTransport"><div className="simPanelTitle"><h3>{en ? 'Analytical sampling sensitivity' : '解析采样密度敏感性'}</h3><span>101 / 201 / 401</span></div><div className="simDataScroll"><table className="simTable"><thead><tr><th>N</th><th>{en ? 'Part' : '部件'}</th><th>max σVM / MPa</th><th>max |u| / mm</th></tr></thead><tbody>{data.branches.flatMap(b => b.parts.map(p => <tr key={`${b.samplingPoints}-${p.id}`}><td>{b.samplingPoints}</td><td>{p.id.toUpperCase()}</td><td>{(Math.max(...p.vonMisesPa) / 1e6).toPrecision(7)}</td><td>{(Math.max(...p.displacementM.map(Math.abs)) * 1000).toPrecision(7)}</td></tr>))}</tbody></table></div><p className="simChartNote">{en ? 'These are analytical sampling densities, not finite-element meshes. Axial stress uses a sampled hoop-stress average, so it and von Mises stress may change with N. This comparison establishes neither mesh-convergence order nor an engineering acceptance criterion.' : '这是解析采样密度，不是有限元网格。轴向应力使用采样环向应力均值，因此自身与等效应力可能随 N 改变；此对照不能确立网格收敛阶或工程验收结论。'}</p></section>
  </>;
}
