'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import ScientificChart from '../components/charts/ScientificChart';
import bundles from './data/physics-bundles.json';
import { loadPhysics, profileDisplay, type PhysicsBundle, type PhysicsData, type Profile, type RZ } from './physics';
import type { SimulationRun } from './contract';
import { downloadJson } from './SimulationPanels';

const names: Record<string, [string, string]> = { te: ['电子温度', 'Electron temperature'], ti: ['平均离子温度', 'Average ion temperature'], ne: ['电子密度', 'Electron density'], q: ['安全因子', 'Safety factor'], pressure: ['平衡压强', 'Equilibrium pressure'], j_tor: ['环向电流密度', 'Toroidal current density'], j_parallel: ['平行电流密度', 'Parallel current density'], j_bootstrap: ['自举平行电流', 'Bootstrap parallel current'], j_ohmic: ['欧姆平行电流', 'Ohmic parallel current'] };
const palette = ['#aa694b', '#327b80', '#7776a6', '#bb923d', '#718b58', '#b56478'];
function profileName(p: Profile, en: boolean) { return names[p.id]?.[en ? 1 : 0] ?? p.label; }
function csv(profile: Profile) {
  const body = [`${profile.axis},${profile.id} [${profile.unit}]`, ...profile.x.map((x, i) => `${x},${profile.y[i] ?? ''}`)].join('\n');
  const url = URL.createObjectURL(new Blob([body], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `${profile.id}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
function ProfileChart({ profile, en, compact = false }: { profile: Profile; en: boolean; compact?: boolean }) {
  const [revision, setRevision] = useState(0);
  const display = profileDisplay(profile); const name = profileName(profile, en);
  return <div className="simProfilePlot">{!compact && <button className="simResetPlot simTinyButton" onClick={()=>setRevision(n=>n+1)}>{en?'Reset view':'重置视图'}</button>}<ScientificChart key={revision} id={`profile-${profile.id}`} height={compact ? 194 : 330} className={compact ? 'simCompactChart' : ''} eager ariaLabel={`${name}; ${display.unit}; ${profile.axis}`} fallbackSrc="" fallbackAlt="" fallback={<p className="simChartNote">{profile.x.length} {en ? 'samples · table and CSV available below' : '个采样点 · 下方可查看数表及 CSV'}</p>} option={{ animation: false, grid: { left: compact ? 52 : 72, right: 24, top: 35, bottom: 38 }, tooltip: { trigger: 'axis', valueFormatter: (v: unknown) => typeof v === 'number' ? v.toPrecision(5) : '—' }, xAxis: { type: 'value', min: profile.x[0], max: profile.x.at(-1), name: profile.axis === 'psi_norm' ? 'ψN' : 'ρtor,N', nameLocation: 'middle', nameGap: 24, splitNumber: 4 }, yAxis: { type: 'value', name: display.unit, nameGap: 12, splitNumber: 3, scale: true }, series: [{ type: 'line', name, data: display.data, showSymbol: false, connectNulls: false, smooth: false, lineStyle: { width: 2, color: palette[['te','ti','ne','q','pressure','j_tor'].indexOf(profile.id)] ?? palette[0] }, itemStyle: { color: palette[0] } }], ...(!compact ? { dataZoom: [{ type: 'inside', filterMode: 'none' }] } : {}) }} /></div>;
}

function Equilibrium({ data, engineering, en }: { data: PhysicsData; engineering: boolean; en: boolean }) {
  const [field, setField] = useState(false); const [wall, setWall] = useState(true); const [contours, setContours] = useState(true); const [pointer, setPointer] = useState<string>('');
  const svg = useRef<SVGSVGElement>(null); const e = data.equilibrium;
  const geometry = data.geometry.layers.flatMap(l => l.outline).concat(data.geometry.coils.flatMap(c => c.elements.flatMap(el => el.outline)));
  const domain = engineering ? [...geometry, ...e.wall, ...e.boundary] : [...e.wall, ...e.boundary];
  const rmin = Math.min(...domain.map(p => p[0])), rmax = Math.max(...domain.map(p => p[0]));
  const zmin = Math.min(...domain.map(p => p[1])), zmax = Math.max(...domain.map(p => p[1]));
  const spanR = rmax - rmin, spanZ = zmax - zmin; const pad = Math.max(spanR, spanZ) * .11;
  const path = (points: RZ) => points.map((p, i) => `${i ? 'L' : 'M'}${p[0]},${-p[1]}`).join(' ');
  const ticks = (lo: number, hi: number) => Array.from({ length: 5 }, (_, i) => lo + (hi - lo) * i / 4);
  const cells = useMemo(() => {
    if (!field || engineering) return [];
    const step = Math.max(1, Math.ceil(Math.sqrt(e.r.length * e.z.length / 4500))); const rows = [];
    for (let j = 0; j < e.z.length - 1; j += step) for (let i = 0; i < e.r.length - 1; i += step) {
      const n = (e.psi[j][i] - e.psiAxis) / (e.psiBoundary - e.psiAxis); if (n < 0 || n > 1) continue;
      rows.push(<rect key={`${i}-${j}`} x={e.r[i]} y={-e.z[Math.min(j+step,e.z.length-1)]} width={e.r[Math.min(i+step,e.r.length-1)]-e.r[i]} height={e.z[Math.min(j+step,e.z.length-1)]-e.z[j]} fill={`hsl(${205-170*n} 45% ${75-25*n}%)`} opacity=".72" />);
    } return rows;
  }, [e, engineering, field]);
  function inspect(event: React.PointerEvent<SVGSVGElement>) {
    const matrix = svg.current?.getScreenCTM(); if (!matrix) return;
    const pt = new DOMPoint(event.clientX, event.clientY).matrixTransform(matrix.inverse()); const r = pt.x, z = -pt.y;
    const nearest = (v: number[], n: number) => v.reduce((best, value, i) => Math.abs(value-n) < Math.abs(v[best]-n) ? i : best, 0);
    const inside = r >= e.r[0] && r <= e.r.at(-1)! && z >= e.z[0] && z <= e.z.at(-1)!;
    const ri=nearest(e.r,r), zi=nearest(e.z,z);
    const psi = inside ? e.psi[zi][ri] : null;
    setPointer(`R ${(inside?e.r[ri]:r).toFixed(3)} m · Z ${(inside?e.z[zi]:z).toFixed(3)} m${psi === null ? '' : ` · ψ ${psi.toPrecision(5)} Wb · ψN ${((psi-e.psiAxis)/(e.psiBoundary-e.psiAxis)).toFixed(3)}`}`);
  }
  function saveSvg() { if (!svg.current) return; const content = new XMLSerializer().serializeToString(svg.current); const url = URL.createObjectURL(new Blob([content], {type:'image/svg+xml'})); const a=document.createElement('a');a.href=url;a.download=`${data.runId}-${engineering?'design':'equilibrium'}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
  return <section className="simPanel simEquilibrium"><div className="simPanelTitle"><h3>{engineering ? (en ? 'Generated design cross-section' : '生成的设计截面') : (en ? 'Poloidal equilibrium' : '极向截面与磁平衡')}</h3><button className="simTinyButton" onClick={saveSvg}>SVG ↓</button></div>
    <div className="simFieldTools"><label><input type="checkbox" checked={wall} onChange={v=>setWall(v.target.checked)} />{en?'Wall':'第一壁'}</label><label><input type="checkbox" checked={contours} onChange={v=>setContours(v.target.checked)} />{en?'Flux surfaces':'磁通面'}</label>{!engineering && <label><input type="checkbox" checked={field} onChange={v=>setField(v.target.checked)} />{en?'ψN field':'ψN 色场'}</label>}<span>R–Z / m</span></div>
    <svg ref={svg} xmlns="http://www.w3.org/2000/svg" className="simEquilibriumSvg" role="img" aria-label={en?'FUSE solved equilibrium in equal-scale R Z coordinates':'FUSE 求解的 R Z 等比例磁平衡截面'} viewBox={`${rmin-pad} ${-zmax-pad} ${spanR+2*pad} ${spanZ+2*pad}`} onPointerMove={inspect} onPointerLeave={()=>setPointer('')}>
      <defs><clipPath id={`plasma-${data.runId}`}><path d={`${path(e.boundary)} Z`} /></clipPath></defs>
      {ticks(rmin,rmax).map(r=><g key={`r${r}`}><path d={`M${r},${-zmin} L${r},${-zmax}`} stroke="var(--color-border, #ddd)" strokeWidth="1" vectorEffect="non-scaling-stroke"/><text x={r} y={-zmin+pad*.6} textAnchor="middle" fontSize={pad*.33} fill="var(--color-ink-muted,#666)">{r.toFixed(1)}</text></g>)}
      {ticks(zmin,zmax).map(z=><g key={`z${z}`}><path d={`M${rmin},${-z} L${rmax},${-z}`} stroke="var(--color-border,#ddd)" strokeWidth="1" vectorEffect="non-scaling-stroke"/><text x={rmin-pad*.25} y={-z} textAnchor="end" dominantBaseline="middle" fontSize={pad*.33} fill="var(--color-ink-muted,#666)">{z.toFixed(1)}</text></g>)}
      {engineering && data.geometry.layers.map((l,i)=><path key={`${l.name}-${i}`} d={`${path(l.outline)} Z`} fill={palette[i%palette.length]} fillOpacity=".18" stroke={palette[i%palette.length]} strokeWidth="1" vectorEffect="non-scaling-stroke"><title>{l.name} · {l.material} · {l.thicknessM ?? '—'} m</title></path>)}
      <g clipPath={`url(#plasma-${data.runId})`}>{cells}</g>
      {wall && <path d={`${path(e.wall)} Z`} fill="none" stroke="var(--color-ink-muted,#777)" strokeWidth="2" vectorEffect="non-scaling-stroke"><title>{en?'First wall':'第一壁'}</title></path>}
      {contours && e.contours.flatMap(c=>c.paths.map((points,i)=><path key={`${c.psiNorm}-${i}`} d={path(points)} fill="none" stroke={`hsl(${205-160*c.psiNorm} 38% 48%)`} strokeWidth="1.25" vectorEffect="non-scaling-stroke"><title>ψN = {c.psiNorm.toFixed(1)}</title></path>))}
      <path d={`${path(e.boundary)} Z`} fill="none" stroke="#b56543" strokeWidth="2.3" vectorEffect="non-scaling-stroke"><title>LCFS</title></path>
      <path d={`M${e.axis[0]-pad*.12},${-e.axis[1]} h${pad*.24} M${e.axis[0]},${-e.axis[1]-pad*.12} v${pad*.24}`} stroke="#b56543" strokeWidth="2" vectorEffect="non-scaling-stroke"><title>{en?'Magnetic axis':'磁轴'}</title></path>
      {engineering && data.geometry.coils.flatMap((c,i)=>c.elements.map((el,j)=><path key={`${i}-${j}`} d={`${path(el.outline)} Z`} fill="#c27e49" fillOpacity=".7" stroke="#8c552f" strokeWidth="1" vectorEffect="non-scaling-stroke"><title>{c.name} · geometry {el.geometryType}</title></path>))}
    </svg><p className="simCoordinate" aria-live="off">{pointer || (en?'Move over the plot to inspect the nearest grid sample':'移动指针查看最近网格点的磁通值')}</p>
    <div className="simPlotLegend"><span>＋ {en?'Magnetic axis':'磁轴'}</span><span>— LCFS</span><span>ψN 0.1–0.9</span><span>COCOS {data.cocos}</span></div><p className="simChartNote">{engineering ? (en?'Parametric design geometry, not CAD or a structural solution. Geometry type 5 uses an equivalent-area outline.':'参数化设计几何，非 CAD 或结构求解结果；几何类型 5 使用等面积轮廓。') : `${e.r.length} × ${e.z.length} ${en?'solved grid · equal metric axes; field preview is sampled, downloads retain every value':'求解网格 · R/Z 米制等比例；色场为采样预览，下载保留全量数据'}`}</p>
  </section>;
}

export default function PhysicsWorkbench({ run, en, engineering = false, trusted }: { run: SimulationRun; en: boolean; engineering?: boolean; trusted: boolean }) {
  const bundle = trusted ? (bundles as PhysicsBundle[]).find(b=>b.runId===run.id && b.recordSha256===run.source.recordSha256 && run.source.artifacts.some(a=>a.name==='physics.json' && a.sha256===b.rawSha256)) : undefined;
  const [state, setState] = useState<{ key: string; data?: PhysicsData; error?: boolean }>({key:''}); const [retry,setRetry]=useState(0); const [group,setGroup]=useState('all'); const [selected,setSelected]=useState('te'); const [table,setTable]=useState(false);
  useEffect(()=>{ const controller=new AbortController(); if(bundle) void loadPhysics(bundle,controller.signal).then(data=>{if(!controller.signal.aborted)setState({key:run.id,data});}).catch(()=>{if(!controller.signal.aborted)setState({key:run.id,error:true});}); return()=>controller.abort(); },[bundle,run.id,retry]);
  const data=state.key===run.id?state.data:undefined;
  if(!bundle) return <div className="simScopeNote"><strong>{en?'Spatial data unavailable':'未提供空间场数据'}</strong><p>{en?'This archive contains only the reported metrics and residuals. No equilibrium, profiles or engineering fields are synthesized to fill the gap.':'此归档仅提供已报告的标量与残差；不生成平衡场、剖面或工程场作为替代。'}</p></div>;
  if(!data) return <div className="simPhysicsLoading" role="status"><span className="simMiniLabel">SCIENTIFIC RESULTS / SHA-256</span><h3>{state.error?(en?'Result verification failed':'结果校验未通过'):(en?'Loading and verifying scientific results…':'正在加载并校验完整计算结果…')}</h3><p>{bundle.grid.join(' × ')} · {bundle.profiles} {en?'profiles':'组剖面'} · {(bundle.bytes/1024).toFixed(0)} KiB</p>{state.error&&<button className="simButton" onClick={()=>{setState({key:run.id});setRetry(n=>n+1);}}>{en?'Retry':'重试加载'}</button>}</div>;
  const profiles=data.profiles.filter(p=>group==='all'||(group==='core'?!p.id.startsWith('source_'):p.id.startsWith('source_'))); const profile=profiles.find(p=>p.id===selected)??profiles[0];
  const mainProfiles=['te','ti','ne','q','pressure','j_tor'].map(id=>data.profiles.find(p=>p.id===id));
  return <div className="simPhysicsResults">
    <div className="simResultMeta"><span className="simGood">● {en?'Integrity verified':'完整性校验通过'}</span><span>{en?'Equilibrium':'平衡'} t = {data.timeSeconds} s</span><span>{en?'Core':'核心'} t = {data.coreTimeSeconds} s</span><span>{data.profiles.length} {en?'profiles':'组剖面'}</span><span>{data.geometry.layers.length} {en?'design layers':'设计层'}</span><button className="simTinyButton" onClick={()=>downloadJson(data,`${run.id}-physics.json`)}>{en?'Full field JSON':'全量场数据 JSON'} ↓</button></div>
    <div className="simScienceGrid"><Equilibrium key={`${data.runId}-${engineering}`} data={data} engineering={engineering} en={en}/>{engineering?<section className="simPanel"><div className="simPanelTitle"><h3>{en?'Design layers & coils':'设计分层与线圈'}</h3><span>{data.geometry.coils.length} PF</span></div><div className="simDataScroll"><table className="simTable"><thead><tr><th>{en?'Layer':'层名称'}</th><th>{en?'Material':'材料'}</th><th>{en?'Thickness / m':'厚度 / m'}</th></tr></thead><tbody>{data.geometry.layers.map((l,i)=><tr key={i}><td>{l.name}</td><td>{l.material}</td><td>{l.thicknessM??'—'}</td></tr>)}</tbody></table></div><div className="simDataScroll"><table className="simTable"><thead><tr><th>{en?'Coil':'线圈'}</th><th>{en?'Time / s':'时刻 / s'}</th><th>{en?'Current / A':'电流 / A'}</th></tr></thead><tbody>{data.geometry.coils.flatMap((c,i)=>c.currentA?.length?c.currentA.map((v,j)=><tr key={`${i}-${j}`}><td>{c.name}</td><td>{c.timeSeconds?.[j]??'—'}</td><td>{v??'—'}</td></tr>):[<tr key={i}><td>{c.name}</td><td>—</td><td>—</td></tr>])}</tbody></table></div></section>:<section className="simProfileGrid" aria-label={en?'Core and equilibrium profiles':'核心与平衡剖面'}>{mainProfiles.map((p,i)=><div className="simPanel simProfileCard" key={i}><header><h3>{p?profileName(p,en):['Te','Ti','ne','q','p','jtor'][i]}</h3><span>{p?.axis==='psi_norm'?'ψN':'ρtor,N'}</span></header>{p?<ProfileChart profile={p} en={en} compact/>:<p className="simChartNote">{en?'Not exported':'未导出'}</p>}</div>)}</section>}</div>
    {(data.timeSeconds!==data.coreTimeSeconds || data.sources.some(s=>s.timeSeconds!==data.timeSeconds)) && <p className="simNotice">{en?'Data blocks have different timestamps; no temporal alignment has been applied.':'不同数据块时刻不一致；尚未进行时间对齐。'}</p>}
    <p className="simScienceBoundary">{en?`SIMULATED · Core transport: ${data.coreTransportModel}. Coupled design-point profiles, not a validated turbulent-transport prediction. Device validation: not established.`:`SIMULATED · 核心输运模型：${data.coreTransportModel}。以上为耦合设计点剖面，不是已验证的湍流输运预测；尚未建立装置验证。`}</p>
    {!engineering&&<section className="simPanel simExplorer"><div className="simPanelTitle"><div><p className="simMiniLabel">RESULT EXPLORER</p><h3>{en?'Complete profile & source inventory':'完整剖面与源项浏览器'}</h3></div><span>{data.profiles.length} {en?'available variables':'个可用变量'}</span></div><div className="simExplorerControls"><label>{en?'Group':'分类'}<select value={group} onChange={e=>setGroup(e.target.value)}><option value="all">{en?'All variables':'全部变量'}</option><option value="core">{en?'Core & equilibrium':'核心与平衡'}</option><option value="sources">{en?'Sources & losses':'源项与损失'}</option></select></label><label className="simVariableSelect">{en?'Variable':'变量'}<select value={profile?.id??''} onChange={e=>setSelected(e.target.value)}>{profiles.map(p=><option key={p.id} value={p.id}>{profileName(p,en)} [{p.unit}]</option>)}</select></label><button className="simButton" aria-pressed={table} onClick={()=>setTable(v=>!v)}>{table?(en?'Show chart':'显示曲线'):(en?'Show table':'显示数表')}</button><button className="simButton" disabled={!profile} onClick={()=>profile&&csv(profile)}>CSV ↓</button></div>{profile&&<><p className="simVariablePath"><code>{profile.source}</code><span>{profile.x.length} {en?'samples':'点'} · {profile.axis} · {profile.unit} · t = {profile.id.startsWith('source_') ? data.sources.find(s=>profile.id.startsWith(s.prefix+'_'))?.timeSeconds ?? '—' : profile.source.startsWith('equilibrium.') ? data.timeSeconds : data.coreTimeSeconds} s</span></p>{table?<div className="simDataScroll"><table className="simTable"><thead><tr><th>#</th><th>{profile.axis}</th><th>{profile.unit}</th></tr></thead><tbody>{profile.x.map((x,i)=><tr key={i}><td>{i+1}</td><td>{x}</td><td>{profile.y[i]??'—'}</td></tr>)}</tbody></table></div>:<ProfileChart key={profile.id} profile={profile} en={en}/>}</>}<p className="simChartNote">{en?'Each variable retains its own radial grid. Source index 1 is an aggregate, not an additional component; signed losses are preserved. Parallel currents are not stacked with toroidal current. CSV uses original SI units.':'每个变量保留独立径向网格。源项 index = 1 为总量，不能再次叠加；损失项保留正负号。平行与环向电流不混加；CSV 使用原始单位。'}</p></section>}
    <details className="simAvailability"><summary>{en?'Data coverage, omissions & native archive':'数据覆盖、缺失项与原生归档'} · {data.unavailable.length} {en?'unavailable fields':'项未提供'}</summary><p>{data.nativeFormat} · IMAS {data.versions.imas}</p><p>{en?'The complete native HDF5 and input configuration are retained with the local run. The web projection exposes only selected, available scientific fields, not every IMAS IDS. No structural stress, CFD or neutronics solution is included.':'完整原生 HDF5 与输入配置保存在本地运行目录。Web 投影公开已选择且实际可用的科学场，不声称覆盖全部 IMAS IDS；没有结构应力、CFD 或中子学求解结果。'}</p><code>{data.unavailable.join(' · ')||'—'}</code></details>
  </div>;
}
