'use client';
import { useState } from 'react';
import ScientificChart from '../components/charts/ScientificChart';
import { useChartTheme } from '../components/charts/chart-theme';
import type { PhysicsData } from './physics';
const channelNames: Record<string,[string,string]> = {electron_heat:['电子热通量','Electron heat flux'],ion_heat:['离子热通量','Ion heat flux'],momentum:['环向动量通量','Toroidal momentum flux'],electron_particles:['电子粒子通量','Electron particle flux']};
export default function TransportResults({data,en}:{data:PhysicsData;en:boolean}) {
  const theme=useChartTheme(); const colors=theme.mode==='dark'?['#81b7ba','#e7a182']:['#327b80','#aa694b'];
  const [table,setTable]=useState(false); const flux=data.fluxMatch, ref=data.reference;
  if(!flux || !ref) return null;
  const line=(name:string,x:number[],y:(number|null)[],dashed=false)=>({name,type:'line',showSymbol:false,connectNulls:false,smooth:false,data:x.map((v,i)=>[v,y[i]]),itemStyle:{color:colors[dashed?0:1]},lineStyle:{color:colors[dashed?0:1],width:2,type:dashed?'dashed':'solid'}});
  const option=(series:unknown[],unit:string)=>({animation:false,legend:{top:4},tooltip:{trigger:'axis'},grid:{left:70,right:25,top:56,bottom:40},xAxis:{type:'value',name:'ρtor,N',nameLocation:'middle',nameGap:27},yAxis:{type:'value',name:unit,scale:true},series});
  return <>
    <section className="simPanel simTransport"><div className="simPanelTitle"><div><p className="simMiniLabel">INPUT → PREDICTION</p><h3>{en?'Initialized reference & predicted profiles':'初始化参考与预测剖面对照'}</h3></div><span>{en?'Reference ≠ raw observations':'参考 ≠ 原始观测'}</span></div><p className="simChartNote">{en?ref.description: data.equilibriumOrigin==='input-reconstruction'?'参考来自上游 L-mode 示例的初始化状态；没有原始诊断、不确定度或可确认的放电号。':'参考是基于上游平衡初始化的参数化剖面，并非装置实测剖面。'} · t = {ref.timeSeconds} s</p><div className="simTransportGrid">{(['te','ti','ne'] as const).map(id=>{
      const p=data.profiles.find(p=>p.id===id); if(!p)return null; const scale=id==='ne'?1e-19:0.001;const unit=id==='ne'?'10¹⁹ m⁻³':'keV';
      return <div key={id}><h4>{id==='te'?'Te':id==='ti'?'Ti':'ne'}</h4><ScientificChart id={`reference-${data.runId}-${id}`} height={270} eager ariaLabel={`${id}: initialized reference versus prediction`} fallbackSrc="" fallbackAlt="" fallback={<p>{en?'Exact samples are in the full JSON download.':'完整 JSON 提供精确采样值。'}</p>} option={option([line(en?'Initialized reference':'初始化参考',ref.rho,ref[id].map(v=>v*scale),true),line(en?'Prediction':'预测',p.x,p.y.map(v=>v===null?null:v*scale))],unit)}/></div>;
    })}</div><p className="simChartNote">{en?'Each curve retains its original grid; no interpolation, fitting score or experimental accuracy claim.':'两条曲线保留各自径向网格；不插值，不给出伪精度或实验验证评分。'}</p></section>
    <section className="simPanel simTransport"><div className="simPanelTitle"><div><p className="simMiniLabel">SOURCE ↔ TRANSPORT</p><h3>{en?'Resolved flux balance':'求解器通量收支'}</h3></div><button className="simButton" aria-pressed={table} onClick={()=>setTable(v=>!v)}>{table?(en?'Show charts':'显示曲线'):(en?'Exact values':'精确数表')}</button></div>
    {flux.stateRelation==='post-coupling-recomputed'&&<p className="simNotice">{en?'These fluxes were recomputed on the final coupled equilibrium. The inner solver residual below belongs to the preceding transport solve, not this post-check.':'通量是在最终耦合平衡上重新计算的独立检查。下方内层残差来自此前输运求解，不是这次后检查的残差。'}</p>}
    <div className="simTransportGrid simFluxGrid">{flux.channels.map(c=><div key={c.id}><h4>{channelNames[c.id]?.[en?1:0]??c.id}</h4>{table?<div className="simDataScroll"><table className="simTable"><thead><tr><th>ρtor,N</th><th>{en?'Source target':'源目标'} / {c.unit}</th><th>{en?'Transport':'输运'} / {c.unit}</th><th>Δ</th></tr></thead><tbody>{flux.rho.map((x,i)=><tr key={x}><td>{x}</td><td>{c.target[i]}</td><td>{c.model[i]}</td><td>{c.model[i]-c.target[i]}</td></tr>)}</tbody></table></div>:<ScientificChart id={`flux-${data.runId}-${c.id}`} height={275} eager ariaLabel={`${c.id} source versus transport ${c.unit}`} fallbackSrc="" fallbackAlt="" fallback={<p>{en?'Switch to exact values for every sample.':'切换精确数表查看全部采样值。'}</p>} option={option([line(en?'Source target':'源目标',flux.rho,c.target,true),line(en?'Transport':'输运',flux.rho,c.model)],c.unit)}/>}</div>)}</div>
    <p className="simChartNote">{en?'Targets are integrated source / flux-surface area, sampled as in FUSE. Signs are preserved. Momentum uses kg/s² from FUSE/GACODE implementation; IMASdd metadata differs (kg/m/s²). No additional radius scaling is applied.':'目标为积分源项除以磁面面积，并按 FUSE 规则取样，保留正负号。动量单位 kg/s² 依据 FUSE/GACODE 实现，与 IMASdd 元数据 kg/m/s² 不同；未额外乘除大半径。'}</p></section>
    <section className="simPanel simTransport"><div className="simPanelTitle"><h3>{flux.stateRelation==='post-coupling-recomputed'?(en?'Last inner solver evaluation history':'最后一轮内层函数评估历史'):(en?'Full inner solver evaluation history':'完整内层函数评估历史')}</h3><span>{flux.evaluationResiduals.length} {en?'evaluations':'次评估'}</span></div><ScientificChart id={`inner-${data.runId}`} height={280} eager ariaLabel={en?'Function evaluation residual history':'函数评估残差历史'} fallbackSrc="" fallbackAlt="" fallback={<p>{en?'All evaluation residuals are retained in the full JSON.':'全部评估残差保留在完整 JSON 中。'}</p>} option={{animation:false,tooltip:{trigger:'axis'},grid:{left:75,right:25,top:35,bottom:50},xAxis:{type:'value',name:en?'Function evaluation index':'函数评估序号',nameLocation:'middle',nameGap:30},yAxis:{type:'log',name:en?'Residual norm':'残差范数'},series:[line(en?'Evaluated residual':'评估残差',flux.evaluationResiduals.map((_,i)=>i+1),flux.evaluationResiduals.map(v=>v===0?null:v))]}}/><p className="simChartNote">{en?'Selected solution residual':'选定解残差'} = {flux.selectedResidual.toPrecision(8)} · xtol = {flux.xtol} {en?'is mapped to residual L∞ abstol by this pinned backend. The final termination L∞ value and retcode are not archived; do not compare it directly with the plotted L2 norm. Strict convergence is not established. Erratum: earlier archive text calling xtol a step tolerance is incorrect; native bytes and numerical values are preserved. Zero values are omitted only on the log plot.':'在此固定版本后端映射为残差 L∞ 的 abstol。终止时 L∞ 值和 retcode 未归档，不可直接与本图 L2 范数比较；严格收敛未确立。勘误：旧归档中“步长容差”的注释不准确，保留原始字节与数值不变。对数图仅省略零值。'}</p></section>
  </>;
}
