'use client';
import ScientificChart from '../../components/charts/ScientificChart';
import { download, number } from '../platform/display';
import type { ControlResult } from './contracts';

export default function ControlResultView({ result: r, en, index, onIndex }: { result: ControlResult; en: boolean; index: number; onIndex: (i: number) => void }) {
  const t = (zh: string, english: string) => en ? english : zh;
  const frame = r.geometry.frames.find(f => f.timeIndex === index);
  return <><section className="transportPanel"><h2>{r.id}</h2><p>{r.origin} · {r.execution.state} · {r.execution.completedSteps}/{r.execution.requestedSteps} steps</p><p>{t('数据检查不等于数值收敛或装置验证。', 'Data checks do not establish numerical convergence or device validation.')}</p><label>{t('原生时间采样', 'Native time sample')} <input type="range" min={0} max={r.time.values.length - 1} value={index} onChange={e => onIndex(Number(e.target.value))} /></label><p>t = {number(r.time.values[index])} s {t('（相对 RESET）', '(relative to RESET)')}</p></section><div className="transportTwoColumns">{r.signals.map(s => <section key={s.id} className="transportPanel"><h3>{s.id} / {s.unit} · {number(s.values[index])}</h3><ScientificChart id={`${r.engine.id}-${s.id}`} ariaLabel={`${s.id} / ${s.unit}`} fallbackSrc="" fallbackAlt="" fallback={<p>{t('可下载完整 JSON 数据。', 'Full JSON data is available for download.')}</p>} height={240} option={{ animation: false, tooltip: { trigger: 'axis' }, xAxis: { type: 'value', name: 't / s' }, yAxis: { type: 'value', name: s.unit, scale: true }, series: [{ type: 'line', showSymbol: false, connectNulls: false, data: r.time.values.map((time, i) => [time, s.values[i]]) }] }} /></section>)}</div>
    <section className="transportPanel"><p>{t('已发送 / 未确认 STEP', 'Dispatched / unconfirmed STEP')}: {r.execution.dispatchedSteps} / {r.execution.unconfirmedSteps}</p><h2>{t('电压命令与发送值', 'Voltage commands and sent values')}</h2><div className="transportTableScroll"><table className="transportTable"><thead><tr><th>Channel</th><th>Command / V</th><th>Sent / V</th><th>Applied / V</th></tr></thead><tbody>{r.actions.channels.map((c, i) => <tr key={c}><td>{c}</td><td>{number(r.actions.commandedV[index][i])}</td><td>{number(r.actions.sentV?.[index][i])}</td><td>—</td></tr>)}</tbody></table></div><p>{t('未报告的实际施加值不以命令值替代。', 'Unreported applied values are not replaced by commands.')}</p></section>
    <section className="transportPanel"><h2>{t('原生边界与场覆盖', 'Native boundary and field coverage')}</h2>{frame ? <ScientificChart id={`${r.engine.id}-lcfs`} ariaLabel="Native LCFS" fallbackSrc="" fallbackAlt="" height={360} option={{ animation: false, xAxis: { type: 'value', name: 'R / m', scale: true }, yAxis: { type: 'value', name: 'Z / m', scale: true }, series: [{ type: 'line', showSymbol: false, data: frame.lcfs }] }} fallback={<p>LCFS: {frame.lcfs.length} points</p>} /> : <p>{t('此时刻无可展示的原生 LCFS；不插值、不生成替代磁面。', 'No native LCFS at this sample; no interpolated or fabricated surface.')}</p>}<p>{r.geometry.reason}</p></section>
    <section className="transportPanel"><h2>{t('数据与来源', 'Data & provenance')}</h2><p>{r.provenance.sourceLabel}</p><p>Git: <code>{r.engine.sourceCommit}</code></p><p>Docker Image ID: <code>{r.engine.imageDigest ?? 'unavailable'}</code></p><p>Raw SHA-256: <code>{r.provenance.resultSha256}</code></p><p>Manifest SHA-256: <code>{r.provenance.manifestSha256}</code></p><ul>{r.limitations.map((s, i) => <li key={i}>{s}</li>)}</ul><button onClick={() => download(`${r.id}.json`, JSON.stringify(r, null, 2))}>{t('下载校验后的 JSON', 'Download validated JSON')}</button></section></>;
}
