export type Facility = {
  name:string; country:string; type:string; status:string; statusClass:string; phase:string; updated:string;
  summary:string; milestone:string; twinValue:string; source:string; url:string; secondSource?:string; thirdSource?:string; featured?:boolean;
};

export const facilities:Facility[] = [
  {name:'EXL-50U',country:'中国 · 新奥',type:'球形环 / p-¹¹B 研究装置',status:'运行中',statusClass:'operate',phase:'装置实验与关键任务验证',updated:'2026-01-18',featured:true,summary:'EXL-50U 是 EXL-50 的升级装置，面向球形环非感应电流启动、高密度热离子模、宽参数能量约束标度及氢硼等离子体研究；主机于 2023 年底完成装配，2024 年 1 月获得首次等离子体。',milestone:'IAEA FEC 2025 综述报告 1 MA 高硼离子占比 p-¹¹B 等离子体、380 kW ECRH 下 270 kA 全非感应电流，以及 AI 支持的 500 kA 电流和位移稳定控制超过 500 ms。2026 年预印本进一步报告 PTEFIT 在 129×129 网格上的平均推理时间为 0.268 ms，并已用于位置与等磁通控制。',twinValue:'最适合形成“装置资产—实时平衡—合成诊断—控制器—实验回放”的窄孪生，并验证 GPU 数值重建、AI 状态估计和控制 sim-to-real。',source:'IAEA FEC 2025：EXL-50U experiments overview',url:'https://conferences.iaea.org/event/392/papers/35644/files/13873-OV2999-EXL-50UOverview-YJShi.pdf',secondSource:'https://pst.hfcas.ac.cn/article/cstr/32219.14.2058-6272/ad9e8f',thirdSource:'https://arxiv.org/abs/2601.12378'},
  {name:'EHL-2',country:'中国 · 新奥',type:'高场球形环 / p-¹¹B 研究平台',status:'设计推进',statusClass:'design',phase:'物理设计与工程设计推进',updated:'2026-08-10',featured:true,summary:'EHL-2（ENN He-Long 2）是新奥下一代球形环平台，目标是在更高磁场和数十 keV 离子温度条件下研究 p-¹¹B 热核反应率、热离子模与球形环约束标度，为后续燃烧等离子体平台提供设计依据。',milestone:'公开标准设计参数约为主半径 1.05 m、纵横比 1.85、环向场 3 T、等离子体电流 3 MA、峰值离子温度超过 30 keV、Ti/Te 大于 2。新奥官网当前将其列为设计阶段，并预计 2027 年中完成建设；IAEA FEC 2025 材料给出了分系统设计、样机试验与建造安装时间线。',twinValue:'天然需要 0D 系统代码、平衡与位形、GENE/输运、快离子、边界排热、加热电流驱动、磁体和电源在同一配置基线中迭代，是从集成模拟走向设计数字孪生的关键案例。',source:'新奥能源研究院：EHL-2 官方页面',url:'https://en.ennresearch.com/researchfield/Compactfusion/EHL_2/',secondSource:'https://pst.hfcas.ac.cn/cn/article/pdf/preview/10.1088/2058-6272/ad981a.pdf',thirdSource:'https://conferences.iaea.org/event/392/papers/35908/files/13899-FEC2025_EHL2-Manuscript-Xie-V6.pdf'},
  {name:'ITER',country:'法国 / 国际',type:'大型燃烧等离子体 Tokamak',status:'装配中',statusClass:'build',phase:'机器装配与系统调试准备',updated:'2026-07-29',summary:'按 Baseline 2024 推进机器和厂房系统装配。ITER 是验证燃烧等离子体、超导磁体、核级装置集成与远程维护的国际基准。',milestone:'9 个真空室扇区模块中已有 6 个进入托卡马克大厅，中央螺线管 6 个模块完成堆叠。',twinValue:'超大装配配置、IMAS 数据模型、综合控制与装置级合成诊断。',source:'ITER Organization：Two-thirds of tokamak core now in place',url:'https://www.iter.org/two-thirds-iter-tokamak-core-now-place',secondSource:'https://www.iter.org/project/tokamak-assembly'},
  {name:'SPARC',country:'美国',type:'高场紧凑 Tokamak',status:'建设中',statusClass:'build',phase:'设施调试与主机装配',updated:'2026-05-14',summary:'CFS 在 Devens 建设用于验证净聚变能条件的高场 HTS Tokamak，并把建设和调试经验同步反馈到 ARC 电厂设计。',milestone:'2026 年 4 月官方披露设施约完成 75%；真空室两半和首批 TF 磁体进入主机装配，官方更新称计划 2027 年开始运行。',twinValue:'PLM 主数据、physics-to-engineering workflow、HTS 磁体数字线程与 ARC 设计反馈。',source:'CFS：SPARC facility about 75% done',url:'https://blog.cfs.energy/our-sparc-fusion-facility-is-now-about-75-done-take-a-virtual-tour-of-the-progress/',secondSource:'https://blog.cfs.energy/cfs-begins-preparing-a-home-for-our-100-million-degree-fusion-plasma/'},
  {name:'BEST',country:'中国',type:'紧凑燃烧等离子体 Tokamak',status:'建设中',statusClass:'build',phase:'主机全面装配',updated:'2026-01-19',summary:'由中科院合肥物质院等离子体所牵头，目标是在紧凑装置上开展氘氚燃烧等离子体并探索聚变发电演示。',milestone:'2025 年 5 月开始全面装配，低温杜瓦底座于 2025 年 10 月安装；官方计划 2027 年底完成装置。',twinValue:'从 EAST 数据到燃烧等离子体装置的设计—建造—调试数字线程。',source:'HFIPS/CAS：BEST key component installed',url:'https://english.hf.cas.cn/nr/bth/202510/t20251009_1075255.html',secondSource:'https://english.hf.cas.cn/nr/hm/202601/t20260119_1145868.html'},
  {name:'DTT',country:'意大利',type:'偏滤器试验 Tokamak',status:'建设中',statusClass:'build',phase:'场址基础设施与部件研制',updated:'2026-05-13',summary:'DTT 面向 ITER/DEMO 相关排热条件，测试多种偏滤器与核心—边界一体化运行方案。',milestone:'2026 年初托卡马克大厅及新建筑结构工程启动；ECRH 建筑、磁体导体和 RF 系统采购与资格测试同步推进。',twinValue:'高热流部件、偏滤器工程、超导磁体、远程维护与配置受控虚拟样机。',source:'DTT Project：construction keeps moving forward',url:'https://www.dtt-project.it/index.php/news-events/dtt-construction-keeps-moving-forward.html',secondSource:'https://dtt-project.it/at-the-start-structural-works-for-the-dtt-project-at-enea-frascati-research-centre/'},
  {name:'JT-60SA',country:'日本 / 欧盟',type:'大型超导 Tokamak',status:'维护增强',statusClass:'upgrade',phase:'ME1 / OP2 准备',updated:'2026-06',summary:'2023 年获得首次等离子体后，装置进入维护增强阶段，并开始无等离子体综合调试，为下一轮运行做准备。',milestone:'2026 年官方运行培训材料确认 JT-60SA 处于 ME1，OP2 准备和 integrated commissioning without plasma 已启动。',twinValue:'场景设计、自由边界、控制器、合成诊断和操作员流程的完整虚拟放电链。',source:'JT-60SA：2026 operations training call',url:'https://www.jt60sa.org/wp/wp-content/uploads/2026/06/Call_for_participation_in_operations_training_v5-1.pdf',secondSource:'https://www.jt60sa.org/wp/operation/'},
  {name:'STEP',country:'英国',type:'球形 Tokamak 原型电厂',status:'初步设计',statusClass:'design',phase:'概念设计转初步设计',updated:'2026-07',summary:'英国计划在 West Burton 建设面向净电力、氚自持与可维护性的原型聚变电厂，目标时间指向 2040。',milestone:'2026 年公开材料表明项目已由概念设计转入初步设计，并继续更新等离子体与整厂集成基线。',twinValue:'系统代码、参数化 CAD、RAMI、维护、氚循环与全电厂配置管理。',source:'UKAEA/UKIFS：STEP updated plasma scenario',url:'https://indico.ukaea.uk/event/449/contributions/1223/',secondSource:'https://step.ukaea.uk/'},
  {name:'EAST',country:'中国',type:'全超导长脉冲 Tokamak',status:'运行中',statusClass:'operate',phase:'长脉冲稳态实验',updated:'2025-01-21',summary:'EAST 持续研究稳态运行、主动冷却壁、加热电流驱动、控制与等离子体—材料相互作用。',milestone:'2025 年实现 1,066 秒稳态高约束模等离子体，形成装置运行、热工与诊断验证的重要数据基线。',twinValue:'长脉冲状态估计、控制代理、PFC 热状态、低温与工程系统校准。',source:'Chinese Academy of Sciences：EAST 1,066 s milestone',url:'https://english.cas.cn/special-reports/2025q1/202512/t20251219_1138417.shtml',secondSource:'https://english.hf.cas.cn/r/ResearchPrograms/PlasmaPhysics/'},
  {name:'KSTAR',country:'韩国',type:'全超导长脉冲 Tokamak',status:'运行中',statusClass:'operate',phase:'钨偏滤器运行与控制开发',updated:'2025-10-16',summary:'KSTAR 已进入主动冷却钨单块偏滤器运行阶段，重点发展反应堆相关长脉冲与实时控制。',milestone:'公开的 2023—2025 运行证据包括钨偏滤器调试、约 100 秒高性能长脉冲以及钨杂质和脱靶控制研究。',twinValue:'Virtual KSTAR、PCS/诊断接口、实时控制代理与模块化装置场景。',source:'IAEA FEC 2025：KSTAR overview',url:'https://conferences.iaea.org/event/392/papers/35589/files/13907-Manuscript_2025FEC_KSTAROV_v4.pdf',secondSource:'https://doi.org/10.1016/j.fusengdes.2025.115249'},
  {name:'Wendelstein 7-X',country:'德国',type:'优化仿星器',status:'维护/开机准备',statusClass:'upgrade',phase:'维护结束与 OP2.4 准备',updated:'2026-07-27',summary:'W7-X 用于验证优化仿星器的稳态运行能力，是 Tokamak 之外的重要数字孪生与长脉冲工程参照。',milestone:'官方日程显示 2025 年 6 月至 2026 年 8 月维护，OP2.4 计划于 2026 年 9—12 月开展。',twinValue:'三维磁构型、线圈误差、长脉冲热状态与稳态控制。',source:'IPP：W7-X Call for Proposals OP2.4/2.5',url:'https://www.ipp.mpg.de/w7xproposals',secondSource:'https://www.ipp.mpg.de/hipmib26en'},
  {name:'MAST Upgrade',country:'英国',type:'球形 Tokamak',status:'运行中',statusClass:'operate',phase:'多轮实验与 Super-X 验证',updated:'2025',summary:'MAST-U 聚焦先进排热、球形 Tokamak 物理和未来电厂关键技术，多机构实验计划持续推进。',milestone:'EUROfusion 公开信息显示其第四轮实验由百余名研究人员参与，Super-X 等排热概念继续形成 STEP 的物理和工程证据。',twinValue:'先进偏滤器、热流测量、工程 ROM、虚拟验证与 STEP 设计反馈。',source:'EUROfusion：European labs research update',url:'https://euro-fusion.org/eurofusion-news/european-labs-lead-the-way-europes-fusion-energy-research-in-full-swing/'},
  {name:'DIII-D',country:'美国',type:'先进 Tokamak',status:'运行中',statusClass:'operate',phase:'高性能场景、AI 与控制实验',updated:'2026',summary:'DIII-D 以灵活构型、丰富诊断和控制系统支撑先进场景、边界、三维场、AI 控制及 ITER/电厂研究。',milestone:'装置长期开放给美国与国际合作团队；当前数字孪生价值主要来自高质量历史放电、实时控制和 physics-to-engineering 工作流。',twinValue:'OMFIT/OMAS、HEAT、ThinCurr、代理输运、实时稳定性和控制 sim-to-real。',source:'General Atomics：DIII-D National Fusion Facility',url:'https://www.ga.com/magnetic-fusion/diii-d'},
  {name:'JET',country:'英国 / 欧洲',type:'大型氘氚 Tokamak',status:'退役过渡',statusClass:'retire',phase:'再利用与退役',updated:'2024-01-17',summary:'JET 已完成 40 年等离子体运行，作为具有氘氚燃料和 ITER 类壁的关键装置进入退役与知识保全阶段。',milestone:'最后一次等离子体为 2023 年 12 月 18 日的第 105,842 炮；最终 D-T 计划取得 69.26 MJ 聚变能纪录。',twinValue:'氘氚中子学、活化、停机剂量、材料与退役数字线程的不可替代验证集。',source:'EUROfusion：JET final plasma',url:'https://euro-fusion.org/member-news/pioneering-jet-delivers-final-plasma/',secondSource:'https://euro-fusion.org/eurofusion-news/dte3record/'},
];
