'use client';
import {useMemo, useState} from 'react';
import Link from 'next/link';
import SiteFooter from '../components/SiteFooter';
import SiteNav from '../components/SiteNav';
import { useI18n } from '../i18n';
import {facilities} from './data';
import './facilities.css';

const statusEn:Record<string,string>={
  '全部':'All','建设中':'Under construction','运行中':'Operating','设计推进':'Design development','维护增强':'Maintenance / enhancement',
  '维护/开机准备':'Maintenance / campaign preparation','初步设计':'Preliminary design','退役过渡':'Decommissioning transition','装配中':'Assembly',
};

const facilityEn:Record<string,{country:string;type:string;phase:string;summary:string;milestone:string;twinValue:string;source:string}>={
  'EXL-50U':{country:'China · ENN',type:'Spherical tokamak / p-11B research device',phase:'Experimental operation and mission validation',summary:'EXL-50U is the upgraded successor to EXL-50. Its programme addresses non-inductive current initiation in a spherical tokamak, high-density hot-ion regimes, broad-parameter energy-confinement scaling and hydrogen–boron plasma research. Assembly was completed in late 2023 and first plasma was achieved in January 2024.',milestone:'The IAEA FEC 2025 overview reports a 1 MA p-11B plasma with a high boron-ion fraction, 270 kA fully non-inductive current under 380 kW ECRH, and AI-assisted stabilization of 500 kA plasma current and position for more than 500 ms. A 2026 preprint reports a mean PTEFIT inference time of 0.268 ms on a 129 × 129 grid and deployment in position and isoflux control.',twinValue:'A strong candidate for a narrow digital twin connecting plant assets, real-time equilibrium reconstruction, synthetic diagnostics, controllers and shot replay, while validating GPU numerical reconstruction, AI state estimation and control sim-to-real.',source:'IAEA FEC 2025: EXL-50U experiments overview'},
  'EHL-2':{country:'China · ENN',type:'High-field spherical tokamak / p-11B research platform',phase:'Physics and engineering design development',summary:'EHL-2 (ENN He-Long 2) is ENN’s next-generation spherical-tokamak platform. It is intended to investigate p-11B thermonuclear reaction rates, hot-ion regimes and spherical-tokamak confinement scaling at higher field and ion temperatures of several tens of keV, providing a design basis for later burning-plasma platforms.',milestone:'Published reference parameters include major radius 1.05 m, aspect ratio 1.85, toroidal field 3 T, plasma current 3 MA, peak ion temperature above 30 keV and Ti/Te above 2. ENN lists the project in design with construction completion targeted for mid-2027; IAEA FEC 2025 material presents subsystem design, prototype testing, construction and installation milestones.',twinValue:'The project naturally requires 0-D systems modelling, equilibrium and scenario design, GENE/transport, fast-ion, edge exhaust, heating and current drive, magnets and power supplies to iterate on one configuration baseline—an important transition from integrated simulation to a design digital twin.',source:'ENN Energy Research Institute: official EHL-2 page'},
  'ITER':{country:'France / international',type:'Large burning-plasma tokamak',phase:'Machine assembly and preparation for system commissioning',summary:'ITER is proceeding under the 2024 Baseline with machine and plant-system assembly. It is the international reference for burning-plasma physics, superconducting magnets, nuclear-grade plant integration and remote maintenance.',milestone:'Six of the nine vacuum-vessel sector modules have entered the Tokamak Assembly Hall, and stacking of all six central-solenoid modules has been completed.',twinValue:'Very-large-assembly configuration control, the IMAS data model, integrated control and device-scale synthetic diagnostics.',source:'ITER Organization: Two-thirds of tokamak core now in place'},
  'SPARC':{country:'United States',type:'Compact high-field tokamak',phase:'Facility commissioning and tokamak assembly',summary:'Commonwealth Fusion Systems is building the high-field, HTS SPARC tokamak in Devens to test net-fusion-energy conditions and feed construction and commissioning evidence into the ARC power-plant design.',milestone:'In April 2026 CFS reported the facility to be about 75% complete. The two vacuum-vessel halves and first TF magnets had entered machine assembly, with operations planned to begin in 2027.',twinValue:'PLM master data, physics-to-engineering workflows, an HTS-magnet digital thread and evidence feedback to ARC design.',source:'CFS: SPARC facility about 75% complete'},
  'BEST':{country:'China',type:'Compact burning-plasma tokamak',phase:'Full machine assembly',summary:'Led by the Institute of Plasma Physics, Hefei Institutes of Physical Science, BEST is intended to study deuterium–tritium burning plasmas in a compact device and explore fusion-power demonstration.',milestone:'Full assembly began in May 2025 and the cryostat base was installed in October 2025. The official programme targets machine completion by the end of 2027.',twinValue:'A design–build–commission digital thread that transfers EAST evidence to a burning-plasma device.',source:'HFIPS/CAS: BEST key component installed'},
  'DTT':{country:'Italy',type:'Divertor Test Tokamak',phase:'Site infrastructure and component manufacture',summary:'DTT will test divertor concepts and integrated core–edge operating scenarios at exhaust conditions relevant to ITER and DEMO.',milestone:'Structural work for the tokamak hall and new buildings started in early 2026, while ECRH buildings, magnet conductors and RF-system procurement and qualification progressed in parallel.',twinValue:'High-heat-flux components, divertor engineering, superconducting magnets, remote maintenance and a configuration-controlled virtual prototype.',source:'DTT Project: construction keeps moving forward'},
  'JT-60SA':{country:'Japan / European Union',type:'Large superconducting tokamak',phase:'Maintenance Enhancement 1 / preparation for OP2',summary:'Following first plasma in 2023, JT-60SA entered a maintenance-enhancement phase and began integrated commissioning without plasma in preparation for the next operating campaign.',milestone:'Official 2026 operations-training material confirms JT-60SA is in ME1 and that preparation for OP2, including integrated commissioning without plasma, has begun.',twinValue:'A complete virtual-shot chain for scenario design, free-boundary equilibrium, controllers, synthetic diagnostics and operator procedures.',source:'JT-60SA: 2026 operations training call'},
  'STEP':{country:'United Kingdom',type:'Spherical-tokamak prototype power plant',phase:'Concept-to-preliminary design transition',summary:'The United Kingdom plans to build STEP at West Burton as a prototype fusion power plant addressing net electricity, tritium self-sufficiency and maintainability, with a target horizon around 2040.',milestone:'Public material from 2026 shows the programme moving from concept into preliminary design while continuing to update its plasma and whole-plant integration baseline.',twinValue:'Systems codes, parametric CAD, RAMI, maintenance, the tritium cycle and whole-plant configuration management.',source:'UKAEA/UKIFS: STEP updated plasma scenario'},
  'EAST':{country:'China',type:'Fully superconducting long-pulse tokamak',phase:'Long-pulse steady-state experiments',summary:'EAST investigates steady-state operation, actively cooled plasma-facing components, heating and current drive, control and plasma–material interaction.',milestone:'In 2025 EAST sustained a steady-state high-confinement plasma for 1,066 s, providing an important evidence baseline for machine operation, thermal systems and diagnostic validation.',twinValue:'Long-pulse state estimation, control surrogates, PFC thermal state, cryogenics and engineering-system calibration.',source:'Chinese Academy of Sciences: EAST 1,066 s milestone'},
  'KSTAR':{country:'Republic of Korea',type:'Fully superconducting long-pulse tokamak',phase:'Tungsten-divertor operation and control development',summary:'KSTAR now operates with an actively cooled tungsten monoblock divertor, focusing on reactor-relevant long pulses and real-time control.',milestone:'Published 2023–2025 evidence includes tungsten-divertor commissioning, high-performance pulses approaching 100 s, and studies of tungsten-impurity and detachment control.',twinValue:'Virtual KSTAR, PCS/diagnostic interfaces, real-time control surrogates and modular machine scenarios.',source:'IAEA FEC 2025: KSTAR overview'},
  'Wendelstein 7-X':{country:'Germany',type:'Optimized stellarator',phase:'End of maintenance and preparation for OP2.4',summary:'Wendelstein 7-X tests steady-state operation in an optimized stellarator and provides an important non-tokamak reference for digital twins and long-pulse engineering.',milestone:'The official schedule places maintenance from June 2025 through August 2026, with OP2.4 planned for September–December 2026.',twinValue:'Three-dimensional magnetic configuration, coil-error fields, long-pulse thermal state and steady-state control.',source:'IPP: W7-X Call for Proposals OP2.4/2.5'},
  'MAST Upgrade':{country:'United Kingdom',type:'Spherical tokamak',phase:'Multi-campaign operation and Super-X validation',summary:'MAST Upgrade focuses on advanced exhaust, spherical-tokamak physics and enabling technology for future power plants through continuing multi-institutional campaigns.',milestone:'EUROfusion reports that more than one hundred researchers participated in its fourth experimental campaign; exhaust concepts including Super-X continue to build physics and engineering evidence for STEP.',twinValue:'Advanced divertors, heat-flux measurements, engineering reduced-order models, virtual validation and feedback to STEP design.',source:'EUROfusion: European laboratories research update'},
  'DIII-D':{country:'United States',type:'Advanced tokamak',phase:'High-performance scenarios, AI and control experiments',summary:'DIII-D combines flexible plasma shaping, extensive diagnostics and control systems to support advanced scenarios, edge physics, three-dimensional fields, AI control and ITER/power-plant research.',milestone:'The facility remains open to United States and international collaborators. Its digital-twin value derives chiefly from high-quality historical shots, real-time control and physics-to-engineering workflows.',twinValue:'OMFIT/OMAS, HEAT, ThinCurr, surrogate transport, real-time stability assessment and control sim-to-real.',source:'General Atomics: DIII-D National Fusion Facility'},
  'JET':{country:'United Kingdom / Europe',type:'Large deuterium–tritium tokamak',phase:'Repurposing and decommissioning',summary:'After forty years of plasma operation, JET has entered decommissioning and knowledge-preservation activities as the principal device with deuterium–tritium fuel and an ITER-like wall.',milestone:'The final plasma was shot 105,842 on 18 December 2023. The final D–T campaign established a fusion-energy record of 69.26 MJ.',twinValue:'An irreplaceable validation set for D–T neutronics, activation, shutdown dose, materials and decommissioning digital threads.',source:'EUROfusion: JET final plasma'},
};

export default function FacilitiesPage(){
  const { locale }=useI18n();
  const en=locale==='en';
  const [filter,setFilter]=useState('全部');
  const filters=['全部','建设中','运行中','设计推进','维护增强','维护/开机准备','初步设计','退役过渡'];
  const visible=useMemo(()=>filter==='全部'?facilities:facilities.filter(item=>item.status===filter),[filter]);
  return <main className="facilitiesPage">
    <SiteNav active="facilities" />
    <header className="facilitiesHero"><div><p>GLOBAL FUSION FACILITIES / STATUS OBSERVATORY</p><h1>{en?'Global fusion facilities':'全球聚变装置'}<br/><span>{en?'construction and operations observatory':'建设与运行观测台'}</span></h1><div>{en?'An evidence-led record of each facility’s current phase, published milestones and significance for digital-twin architecture, based on official project pages, institutional reports and primary papers.':'以官方项目页面、机构报告和原始论文为证据，记录装置当前阶段、公开里程碑及其对数字孪生技术路线的意义。'}</div></div><aside><span><b>{facilities.length}</b>{en?' priority facilities / projects':'重点装置/项目'}</span><span><b>7</b>{en?' lifecycle states':'生命周期状态'}</span><span><b>2026-08-10</b>{en?' evidence cut-off':'本页核验截止'}</span></aside></header>
    <section className="facilityContext"><div><p>{en?'HOW TO READ':'如何阅读'}</p><h2>{en?'Status is not a ranking; it locates model requirements along the facility lifecycle.':'状态不是排名，而是模型需求的生命周期坐标。'}</h2></div><div><p>{en?'Construction emphasizes CAD/PLM, assembly, supply chain, testing and configuration control. Operation emphasizes experiment synchronization, state estimation and control. Maintenance and decommissioning emphasize asset history, radiation, robotics and knowledge preservation.':'建设阶段强调 CAD/PLM、装配、供应链、测试与配置控制；运行阶段强调实验同步、状态估计和控制；维护与退役阶段则强调资产履历、辐射、机器人与知识保全。'}</p><p>{en?'Published schedules can change. Every card retains an evidence date and source links; time-dependent claims should be checked against those sources.':'项目公开计划会变化。每张卡片都保留核验日期和来源链接，时间性结论以来源为准。'}</p></div></section>
    <section className="facilityAtlas"><div className="facilityFilters" aria-label={en?'Filter facilities by lifecycle state':'按状态筛选'}>{filters.map(item=><button className={filter===item?'active':''} key={item} onClick={()=>setFilter(item)}>{en?statusEn[item]:item}</button>)}</div><div className="facilityGrid">{visible.map((item,index)=>{const translated=facilityEn[item.name];return <article className={item.featured?'featured':''} key={item.name}><header><span>{String(index+1).padStart(2,'0')}</span><b className={item.statusClass}>{en?statusEn[item.status]??item.status:item.status}</b></header><p className="facilityPlace">{en?translated.country:item.country} · {en?translated.type:item.type}</p><h2>{item.name}</h2><h3>{en?translated.phase:item.phase}</h3><p>{en?translated.summary:item.summary}</p><dl><div><dt>{en?'Published milestone':'公开里程碑'}</dt><dd>{en?translated.milestone:item.milestone}</dd></div><div><dt>{en?'Digital-twin value':'孪生价值'}</dt><dd>{en?translated.twinValue:item.twinValue}</dd></div><div><dt>{en?'Evidence checked':'核验日期'}</dt><dd>{item.updated}</dd></div></dl><footer><a href={item.url} target="_blank" rel="noreferrer">{en?translated.source:item.source} ↗</a>{item.secondSource&&<a href={item.secondSource} target="_blank" rel="noreferrer">{en?'Supporting paper':'补充论文'} ↗</a>}{item.thirdSource&&<a href={item.thirdSource} target="_blank" rel="noreferrer">{en?'Additional evidence':'扩展证据'} ↗</a>}</footer></article>})}</div></section>
    <section className="platformInlineLink"><span>{en?'Every card retains its public sources and evidence date.':'每张卡片保留公开来源与核验日期。'}</span><Link href="/platform#architecture">{en?'View the facility-data integration architecture':'查看装置数据接入架构'} →</Link></section>
    <SiteFooter />
  </main>;
}
