import {
  AGENT_CANVAS_LIMITS,
  type AgentCanvasArtifact,
  type AgentTurnCitation,
} from './contracts';

export type AgentCanvasLocale = 'zh-CN' | 'en';

export const LOCAL_CANVAS_LIMITS = Object.freeze({
  maxChars: 80_000,
  maxCitationsPerArtifact: 24,
  maxCitationLabelChars: 180,
  maxCitationTitleChars: 180,
  maxCitationKindChars: 60,
  maxCitationUrlChars: 2_048,
  maxTurnIdChars: 64,
});

export type CanvasCitationInput = Pick<AgentTurnCitation, 'ref' | 'label' | 'url' | 'kind' | 'entryTitle'>;

export type CanvasArtifactInput = AgentCanvasArtifact & {
  /** Generated by the client for the completed assistant turn, never by the model. */
  sourceTurnId: string;
  /** Verified response citations, kept separate from model-authored Canvas markdown. */
  citations: readonly CanvasCitationInput[];
};

export type CanvasPreviewBlock =
  | { kind: 'heading'; level: 1 | 2 | 3; text: string }
  | { kind: 'paragraph'; text: string }
  | { kind: 'list'; items: string[] }
  | { kind: 'code'; text: string };

export function canvasStorageKey(locale: AgentCanvasLocale) {
  return `fusiondigital.agent-canvas.v1.${locale === 'en' ? 'en' : 'zh-CN'}`;
}

export function canPersistCanvasDraft(loadedKey: string | null, currentKey: string) {
  return loadedKey === currentKey;
}

/**
 * Append a verified or user-selected assistant artifact to the local Canvas.
 * The result remains plain text and is bounded before it reaches storage or
 * the renderer; the Canvas never treats model output as HTML.
 */
export function appendCanvasArtifact(current: string, artifact: CanvasArtifactInput) {
  const title = cleanCanvasText(artifact.title, AGENT_CANVAS_LIMITS.maxTitleCharacters)
    .replace(/\s+/g, ' ');
  const content = cleanCanvasText(artifact.content, AGENT_CANVAS_LIMITS.maxContentCharacters);
  if (artifact.kind !== 'markdown' || !content) return current.slice(0, LOCAL_CANVAS_LIMITS.maxChars);
  const namespace = turnNamespace(artifact.sourceTurnId);
  if (!namespace) return current.slice(0, LOCAL_CANVAS_LIMITS.maxChars);

  const citations = normalizeCanvasCitations(artifact.citations, namespace);
  const namespacedContent = namespaceKnownCitationRefs(content, citations);
  const heading = `## ${title || 'Canvas artifact'}\n\nTurn namespace: ${namespace}`;
  const sources = citations.length
    ? citations.map((citation) => `- [${citation.token}] ${citation.label} | ${citation.entryTitle} | ${citation.kind} | ${citation.url}`).join('\n')
    : '- No verified citations were attached to this turn / 本轮未附带可验证引用';
  const appendix = `### Sources / 来源 · ${namespace}\n\n${sources}`;
  const fixedCharacters = heading.length + appendix.length + 4;
  const boundedContent = namespacedContent.slice(0, Math.max(0, LOCAL_CANVAS_LIMITS.maxChars - fixedCharacters));
  const addition = `${heading}\n\n${boundedContent}\n\n${appendix}`;
  const separator = '\n\n---\n\n';
  const sections = current.trim()
    ? current.trim().split(separator).filter(Boolean)
    : [];
  sections.push(addition);
  while (sections.length > 1 && sections.join(separator).length > LOCAL_CANVAS_LIMITS.maxChars) {
    sections.shift();
  }
  return sections.join(separator).slice(0, LOCAL_CANVAS_LIMITS.maxChars);
}

/**
 * Parse a deliberately small Markdown subset into data for escaped React
 * nodes. Unsupported syntax stays visible as text instead of being executed.
 */
export function canvasPreviewBlocks(value: string): CanvasPreviewBlock[] {
  const lines = cleanCanvasText(value, LOCAL_CANVAS_LIMITS.maxChars).split('\n');
  const blocks: CanvasPreviewBlock[] = [];
  let index = 0;

  while (index < lines.length) {
    const line = lines[index];
    if (!line.trim()) {
      index += 1;
      continue;
    }

    if (/^```/.test(line.trim())) {
      const code: string[] = [];
      index += 1;
      while (index < lines.length && !/^```/.test(lines[index].trim())) {
        code.push(lines[index]);
        index += 1;
      }
      if (index < lines.length) index += 1;
      blocks.push({ kind: 'code', text: code.join('\n') });
      continue;
    }

    const heading = /^(#{1,3})\s+(.+)$/.exec(line.trim());
    if (heading) {
      blocks.push({ kind: 'heading', level: heading[1].length as 1 | 2 | 3, text: heading[2] });
      index += 1;
      continue;
    }

    if (/^[-*]\s+/.test(line.trim())) {
      const items: string[] = [];
      while (index < lines.length && /^[-*]\s+/.test(lines[index].trim())) {
        items.push(lines[index].trim().replace(/^[-*]\s+/, ''));
        index += 1;
      }
      blocks.push({ kind: 'list', items });
      continue;
    }

    const paragraph: string[] = [line.trim()];
    index += 1;
    while (
      index < lines.length
      && lines[index].trim()
      && !/^(?:#{1,3}\s+|[-*]\s+|```)/.test(lines[index].trim())
    ) {
      paragraph.push(lines[index].trim());
      index += 1;
    }
    blocks.push({ kind: 'paragraph', text: paragraph.join(' ') });
  }

  return blocks;
}

function cleanCanvasText(value: unknown, limit: number) {
  return typeof value === 'string'
    ? value
      .normalize('NFKC')
      .replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g, ' ')
      .trim()
      .slice(0, limit)
    : '';
}

type NormalizedCanvasCitation = {
  ref: string;
  token: string;
  label: string;
  url: string;
  kind: string;
  entryTitle: string;
};

function normalizeCanvasCitations(
  value: readonly CanvasCitationInput[] | undefined,
  namespace: string,
): NormalizedCanvasCitation[] {
  if (!Array.isArray(value)) return [];
  const seen = new Set<string>();
  const citations: NormalizedCanvasCitation[] = [];
  for (const candidate of value) {
    if (!candidate || typeof candidate !== 'object') continue;
    const ref = typeof candidate.ref === 'string' && /^S\d{1,3}$/.test(candidate.ref)
      ? candidate.ref
      : '';
    const url = safeCitationUrl(candidate.url);
    if (!ref || !url || seen.has(ref)) continue;
    seen.add(ref);
    citations.push({
      ref,
      token: `${namespace}:${ref}`,
      label: cleanCanvasText(candidate.label, LOCAL_CANVAS_LIMITS.maxCitationLabelChars).replace(/\s+/g, ' ') || ref,
      entryTitle: cleanCanvasText(candidate.entryTitle, LOCAL_CANVAS_LIMITS.maxCitationTitleChars).replace(/\s+/g, ' ') || 'Untitled source',
      kind: cleanCanvasText(candidate.kind, LOCAL_CANVAS_LIMITS.maxCitationKindChars).replace(/\s+/g, ' ') || 'source',
      url,
    });
    if (citations.length >= LOCAL_CANVAS_LIMITS.maxCitationsPerArtifact) break;
  }
  return citations;
}

function namespaceKnownCitationRefs(content: string, citations: readonly NormalizedCanvasCitation[]) {
  const tokens = new Map(citations.map((citation) => [citation.ref, citation.token]));
  return content
    .replace(/\[(S\d{1,3})\]\([^\r\n)]{0,2048}\)/g, (match, ref: string) => {
      const token = tokens.get(ref);
      // Citation destinations authored in model markdown are never trusted.
      // A matching URL is reproduced only from the structured turn citation.
      return token ? `[${token}]` : `[${ref}]`;
    })
    .replace(/\[(S\d{1,3})\]/g, (match, ref: string) => {
      const token = tokens.get(ref);
      return token ? `[${token}]` : match;
    });
}

function turnNamespace(value: unknown) {
  const normalized = cleanCanvasText(value, LOCAL_CANVAS_LIMITS.maxTurnIdChars)
    .replace(/[^a-zA-Z0-9_-]/g, '-');
  return normalized ? `turn:${normalized}` : '';
}

function safeCitationUrl(value: unknown) {
  if (typeof value !== 'string' || value.length > LOCAL_CANVAS_LIMITS.maxCitationUrlChars) return '';
  try {
    const url = new URL(value);
    if ((url.protocol !== 'https:' && url.protocol !== 'http:') || url.username || url.password) return '';
    const normalized = url.href;
    return normalized.length <= LOCAL_CANVAS_LIMITS.maxCitationUrlChars ? normalized : '';
  } catch {
    return '';
  }
}
