'use client';
import { capabilities, engines } from './catalog';
export default function EngineOverview({ en, onTorax, onFuse }: { en: boolean; onTorax: () => void; onFuse: () => void }) {
  const t = (zh: string, english: string) => en ? english : zh;
  return <main className="transportStudio"><header className="transportHeading"><div><p className="transportEyebrow">CONNECTED PHYSICS</p><h1>{t('引擎协同', 'Engine collaboration')}</h1><p>{t('从可追溯的单次计算，走向可组合的研究流程。', 'Build composable studies from traceable individual runs.')}</p></div><span className="transportBadge">SIMULATED</span></header>
    <section className="transportPanel"><h2>{t('FUSE → TORAX：已运行的剖面传递', 'FUSE → TORAX: executed profile handoff')}</h2><div className="enginePipeline"><button onClick={onFuse}><small>01 · FUSE</small><strong>{t('DIII-D 物理运行', 'DIII-D physics run')}</strong><span>{t('有来源的模拟剖面', 'Traceable simulated profiles')}</span></button><span aria-hidden="true">→</span><div><small>02 · Te / Ti / ne</small><strong>{t('单位与坐标映射', 'Units & coordinates')}</strong><span>eV → keV · ρtor · SHA-256</span></div><span aria-hidden="true">→</span><button onClick={onTorax}><small>03 · TORAX</small><strong>{t('瞬态热输运', 'Transient heat transport')}</strong><span>{t('独立运行与输入血缘', 'Independent run & input lineage')}</span></button></div><p>{t('传递电子温度、离子温度、电子密度初始剖面；在 TORAX 径向单元上逐点验证。接收端采用显式圆截面近似与简化加热，未传递磁平衡、带符号 q 或源项，不构成同一放电的自洽联合求解。', 'Transfers initial Te, Ti and ne with cell-by-cell verification on the TORAX grid. The receiver uses an explicit circular approximation and simplified heating. Equilibrium, signed q and sources are not transferred; this is not a self-consistent joint discharge solution.')}</p></section>
    <section className="transportPanel"><h2>{t('按能力选择引擎', 'Choose engines by capability')}</h2><div className="transportTableScroll"><table className="transportTable"><thead><tr><th>{t('能力', 'Capability')}</th>{engines.map(e => <th key={e.id}>{e.name} {e.version}</th>)}</tr></thead><tbody>{capabilities.map(c => <tr key={c.id}><th>{en ? c.en : c.zh}<small>{en ? c.scopeEn : c.scopeZh}</small></th>{engines.map(e => <td key={e.id}>{e.capabilities.includes(c.id) ? t('支持', 'Supported') : '—'}</td>)}</tr>)}</tbody></table></div><p>{t('能力代表适配范围，运行结果以各算例的数据覆盖与验证状态为准。', 'Capabilities describe adapter scope; each run retains its own coverage and validation status.')}</p></section>
    <div className="transportTwoColumns"><section className="transportPanel"><h2>{t('可替换的计算接口', 'Replaceable computation interfaces')}</h2><p>{t('引擎描述 → 有界配置 → 独立执行器 → 原生结果 → 标准数据投影 → 工作台。新引擎通过声明输入、输出与能力接入；输运展示无需依赖引擎内部结构。', 'Engine descriptor → bounded configuration → isolated execution → native results → standard projection → workbench. New engines declare ports and capabilities; transport views are independent of engine internals.')}</p><p>{t('FUSE 保留 Julia 执行器和磁平衡/工程投影。TORAX 使用 Python/JAX 执行器和时序剖面投影。', 'FUSE retains its Julia runner and equilibrium/engineering projections. TORAX uses a Python/JAX runner and time-series profiles.')}</p></section><section className="transportPanel"><h2>{t('下一阶段的接口', 'Next integration stages')}</h2><p>{t('二维平衡与 IMAS/EQDSK 映射需要统一坐标、符号约定及守恒检查；闭环反馈需要时间推进和重启能力。GPU、HPC、持久队列与多用户权限属于后续运行平台工作。', '2D equilibrium and IMAS/EQDSK exchange require coordinate/sign conventions and conservation checks. Feedback needs time stepping and restart support. GPU, HPC, durable queues and multi-user authorization are future runtime work.')}</p><p>{t('当前已交付本地认证网关、状态/取消、不可变运行目录和数据导入。公开页面提供只读结果浏览。', 'Delivered: authenticated local gateway, status/cancel, immutable run directories and result import. Public pages expose read-only results.')}</p></section></div>
  </main>;
}
