'use client';
import { useMemo, useState } from 'react';
import { domains, references, tools } from '../data';
import { integratedGroups } from '../integrated-data';
import SiteFooter from '../components/SiteFooter';
import KnowledgeBackLink from '../components/KnowledgeBackLink';
import SiteNav from '../components/SiteNav';
import { useI18n } from '../i18n';
import {
  CouplingMatrixChart,
  DecisionTimescaleChart,
  FidelityLatencyChart,
  FrameworkCapabilityChart,
  FrameworkLandscapeChart,
  MaturityGapChart,
  PhysicsRoadmapChart,
  physicsRoadmapStages,
} from './PhysicsCharts';
import '../integrated.css';
import './physics.css';

export default function Home(){
 const [query,setQuery]=useState(''); const [domain,setDomain]=useState('全部');
 const filtered=useMemo(()=>tools.filter(t=>(domain==='全部'||t.domain===domain)&&(`${t.name} ${t.scope} ${t.devices} ${t.stack}`.toLowerCase().includes(query.toLowerCase()))),[query,domain]);
 const { locale } = useI18n();
 const domainEn: Record<string, string> = {
  '全部':'All domains','平衡、重建与控制':'Equilibrium, reconstruction and control','集成输运与场景':'Integrated transport and scenarios','湍流与新经典输运':'Turbulent and neoclassical transport','MHD、稳定性与破裂':'MHD, stability and disruptions','边界、SOL、偏滤器与壁相互作用':'Edge, SOL, divertor and plasma–wall interaction','加热、电流驱动与快离子':'Heating, current drive and fast ions','失控电子与缓解':'Runaway electrons and mitigation','三维平衡与仿星器优化':'3D equilibrium and stellarator optimization','中子学、活化与辐射输运':'Neutronics, activation and radiation transport','氚、材料与等离子体面对部件':'Tritium, materials and plasma-facing components','工程多物理与安全分析':'Engineering multiphysics and safety analysis','系统工程与整厂优化':'Systems engineering and whole-plant optimization','数据、工作流与合成诊断':'Data, workflows and synthetic diagnostics','惯性约束与其他路线（概览）':'Inertial confinement and other concepts',
 };
 const stackEn=(value:string)=>value.replaceAll('优化器','optimization');
 if(locale==='en') return <main className="physicsPage">
  <SiteNav active="physics" /><KnowledgeBackLink />
  <header id="top" className="hero"><div className="heroCopy"><p className="eyebrow">FUSION DIGITAL TWIN · PHYSICS FOUNDATION</p><h1>Physics simulation</h1><p className="lede">Explore equilibrium, transport, MHD and whole-plant models, with tools and original sources.</p><div className="actions"><a className="primary" href="/fusion-physics-simulation-report.pdf">Download report (Chinese)</a><a href="/engineering">Open engineering simulation</a><a href="#catalog">Browse {tools.length} tools</a></div><div className="stats"><span><b>14</b> physics domains</span><span><b>{tools.length}</b> codes and platforms</span><span><b>2026-08</b> evidence cut-off</span></div></div><img src="/figures/fusion-plant-cutaway-image2.png" alt="Scientific cutaway of a tokamak fusion power plant"/></header>
  <section className="thesis"><p>KEY POSITION</p><h2>A digital twin combines models by decision and time scale.</h2><div className="three"><article><b>Control loop</b><p>Milliseconds to seconds: reconstruction, state estimation, actuator response and risk prediction must be deterministic, degradable and auditable.</p></article><article><b>Design loop</b><p>Hours to months: high-fidelity physics and engineering models provide constraints, training data and uncertainty rather than entering a hard real-time loop.</p></article><article><b>Evidence loop</b><p>Every prediction carries its version, inputs, domain of applicability, validation level and uncertainty before it can inform engineering or safety decisions.</p></article></div></section>
  <section id="map" className="map"><div className="sectionHead"><p className="eyebrow">01 / FROM MICROPHYSICS TO THE GRID</p><h2>A fusion power plant spans roughly twenty orders of magnitude</h2><p>Collisions, turbulence, instabilities, wall materials, neutrons, cooling and the grid need distinct solvers, coupling contracts and evidence management.</p></div><img src="/figures/fusion-multiscale-image2.png" alt="Multiscale fusion-physics overview"/><div className="scale"><span>10⁻¹² s<br/><b>Collisions and waves</b></span><span>10⁻⁶–10⁻³ s<br/><b>Turbulence and MHD</b></span><span>seconds–hours<br/><b>Discharge and power cycle</b></span><span>years–decades<br/><b>Life and economics</b></span></div></section>
  <section className="figureAtlas"><div className="sectionHead"><p className="eyebrow">02 / SYSTEM VIEW</p><h2>How models fit together</h2><p>Positions illustrate orders of magnitude and interfaces, not guaranteed solver performance.</p></div><div className="scienceGrid"><figure><DecisionTimescaleChart/><figcaption><b>A · Decision time scales</b> — model windows from real-time control to whole-plant optimization.</figcaption></figure><figure><FidelityLatencyChart/><figcaption><b>B · Multi-fidelity ensemble</b> — solution time versus effective state dimension.</figcaption></figure><figure><CouplingMatrixChart/><figcaption><b>C · Physics interface matrix</b> — row-to-column information flow; level 2 denotes feedback that normally requires iteration.</figcaption></figure><figure><img src="/figures/physics-stack-nature.png" alt="Fusion-physics stack and digital thread"/><figcaption><b>H · Physics stack and digital thread</b> — shared configuration, interfaces and evidence with domain solvers retained.</figcaption></figure></div></section>
  <section id="catalog" className="catalog"><div className="sectionHead"><p className="eyebrow">03 / FILTERABLE TECHNOLOGY RADAR</p><h2>Codes and tools</h2><p>Source access is not decision qualification. Verify the version, applicability domain and reproducibility of inputs.</p></div><div className="filters"><input aria-label="Search physics tools" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a code, device or software stack…"/><select aria-label="Select physics domain" value={domain} onChange={e=>setDomain(e.target.value)}>{domains.map(d=><option value={d} key={d}>{domainEn[d] ?? d}</option>)}</select><span>{filtered.length} / {tools.length}</span></div><div className="cards">{filtered.map((t,i)=><article className="card" key={t.name}><div className="cardTop"><span>{String(i+1).padStart(2,'0')}</span><a href={t.url} target="_blank" rel="noreferrer" aria-label={`Open the primary source for ${t.name}`}>↗</a></div><h3>{t.name}</h3><p className="domain">{domainEn[t.domain] ?? 'Fusion physics'}</p><p>Candidate code or platform in the evidence catalogue. Consult the primary source for supported equations, verification status, licensing and device applicability.</p><dl><div><dt>Software stack</dt><dd>{stackEn(t.stack)}</dd></div><div><dt>Evidence policy</dt><dd>Source availability is recorded separately from validated deployment readiness.</dd></div></dl></article>)}</div></section>
  <section className="loop"><div><p className="eyebrow">04 / CREDIBLE OPERATING LOOP</p><h2>Continuously calibrate model applicability with experiments</h2><p>High-fidelity models explain and extrapolate; fast models estimate and control; diagnostics test predictions; engineering returns thermal, structural, tritium and lifetime limits. All share versioned data contracts and validation records.</p></div><img src="/figures/experiment-model-control-nature.png" alt="Experiment–model–control evidence loop"/></section>
  <section className="architecture"><div className="sectionHead"><p className="eyebrow">05 / ARCHITECTURE AND CREDIBILITY</p><h2>DINA / MEQ extension architecture</h2></div><div className="scienceGrid"><figure><img src="/figures/dina-meq-architecture-nature.png" alt="DINA and MEQ evolution architecture"/><figcaption><b>E · Evolution architecture</b> — retain controlled device asset packs and authoritative solvers, linked to online models and the offline evidence factory.</figcaption></figure><figure><img src="/figures/credibility-ladder-nature.png" alt="Model credibility evidence ladder"/><figcaption><b>F · G0–G5 evidence ladder</b> — running is not the same as being qualified to influence a decision.</figcaption></figure></div></section>
  <section id="integrated" className="integrated"><div className="sectionHead"><p className="eyebrow">06 / INTEGRATED MODELLING</p><h2>Integrated modelling and the operating loop</h2><p>Compare data, pulse, whole-device, plant-design and industrial twin platforms. Scores are editorial planning assessments from public evidence.</p></div><div className="scienceGrid integratedFigures"><figure className="integratedDataFigure"><FrameworkLandscapeChart/><figcaption><b>I · Framework landscape</b> — lifecycle reach and coupling depth.</figcaption></figure><figure className="integratedDataFigure"><FrameworkCapabilityChart/><figcaption><b>J · Capability matrix</b> — inspect framework-to-capability cells.</figcaption></figure><figure><img src="/figures/integrated-to-digital-twin-gap-nature.png" alt="Gap from integrated modelling to a digital twin"/><figcaption><b>L · Critical gaps</b> — state synchronization, online assurance, authority boundaries and lifecycle continuity.</figcaption></figure><figure><img src="/figures/integrated-twin-reference-architecture-nature.png" alt="Two-speed integrated-modelling digital-twin architecture"/><figcaption><b>M · Two-speed architecture</b> — an online operating loop and offline evidence factory connected by controlled configuration and model release.</figcaption></figure></div><div className="gapBand"><div className="gapChartCell"><MaturityGapChart/></div><div><h3>Operating-assurance gaps</h3><p>Integrated modelling still needs state synchronization, worst-case latency tests, out-of-domain detection, safe fallback, asset configuration and continuous V&amp;V.</p><a href="/fusion-physics-simulation-report.pdf">Read the detailed analysis (Chinese) →</a></div></div><div className="frameworkGroups">{integratedGroups.map((g,index)=><article key={g.group}><header><span>{String(index+1).padStart(2,'0')}</span><div><h3>{['Data models and workflow foundations','Pulse and plasma integration suites','Whole-device and high-fidelity engineering','Plant design and industrial twin platforms'][index] ?? 'Integrated-modelling framework'}</h3><p>Candidate frameworks are assessed by interfaces, reproducibility, coupling depth, computational role and device evidence.</p></div></header>{g.items.map(f=><details key={f.name}><summary><b>{f.name}</b><span>Review as a candidate within a controlled, versioned workflow.</span></summary><div className="frameworkDetail"><p><strong>Qualification</strong>Benchmark supported capabilities, convergence, provenance, uncertainty and failure behavior for the intended device decision.</p><a href={f.url} target="_blank" rel="noreferrer">Official or primary source ↗</a></div></details>)}</article>)}</div></section>
  <section id="roadmap" className="roadmap"><div className="sectionHead"><p className="eyebrow">07 / EVIDENCE-GATED ROADMAP</p><h2>Start with DINA / MEQ</h2><p>Each phase delivers a verifiable decision capability.</p></div><PhysicsRoadmapChart/></section>
  <section className="originals"><div className="sectionHead"><p className="eyebrow">08 / PRIMARY RESEARCH EVIDENCE</p><h2>Primary research and model boundaries</h2></div><div className="figureGrid"><figure><img src="/figures/original-digital-framework-fig1.png" alt="Original integrated digital framework figure for a fusion power plant"/><figcaption>Patterson et al.: integrated digital framework for a fusion power plant, Royal Society Open Science, CC BY 4.0.</figcaption></figure><figure><img src="/figures/original-fuse-architecture-fig1.png" alt="Original FUSE architecture figure"/><figcaption>FUSE: IMAS-based ontology and multi-fidelity workflow.</figcaption></figure><figure><img src="/figures/original-dream-validation-fig5-6.png" alt="Original DREAM validation figures"/><figcaption>DREAM verification against analytic and independent-code results.</figcaption></figure><figure><img src="/figures/original-jorek-starwall-fig2.png" alt="Original JOREK–STARWALL coupling figure"/><figcaption>JOREK–STARWALL coupling of plasma, vacuum and conducting structures.</figcaption></figure></div></section>
  <section id="evidence" className="evidence"><div className="sectionHead"><p className="eyebrow">09 / TRACEABLE SOURCES</p><h2>Core publications and official resources</h2><p>Primary sources are linked below; the full report is in Chinese.</p></div><div className="refs">{references.map(r=><a key={r.id} href={r.url} target="_blank" rel="noreferrer"><span>{r.id}</span><h3>Primary source</h3><p>{r.org} · {r.year}</p></a>)}</div></section>
  <SiteFooter />
 </main>;
 return <main className="physicsPage">
  <SiteNav active="physics" />
  <KnowledgeBackLink />
  <header id="top" className="hero"><div className="heroCopy"><p className="eyebrow">聚变数字孪生 · 物理模拟技术底座</p><h1>物理模拟</h1><p className="lede">查找平衡、输运、MHD 与整厂模型，以及对应工具和原始资料。</p><div className="actions"><a className="primary" href="/fusion-physics-simulation-report.pdf">下载物理报告</a><a href="/engineering">进入工程仿真分页</a><a href="#catalog">浏览 {tools.length} 项工具</a></div><div className="stats"><span><b>14</b> 类物理域</span><span><b>{tools.length}</b> 项代码/平台</span><span><b>2026-08</b> 证据截止</span></div></div><img src="/figures/fusion-plant-cutaway-image2.png" alt="托卡马克聚变电厂剖面科学示意图"/></header>
  <section className="thesis"><p>关键判断</p><h2>数字孪生按决策和时间尺度组合模型。</h2><div className="three"><article><b>控制闭环</b><p>毫秒到秒；重建、状态估计、执行器响应和风险预测必须确定、可降级、可审计。</p></article><article><b>设计闭环</b><p>小时到月；高保真物理与工程模型提供约束、训练数据和不确定度，而非直接进入实时回路。</p></article><article><b>证据闭环</b><p>每个预测携带版本、输入、适用域、验证层级和置信区间，才能用于工程与安全决策。</p></article></div></section>
  <section id="map" className="map"><div className="sectionHead"><p className="eyebrow">01 / 从微观到电网</p><h2>一台聚变电厂跨越约二十个数量级</h2><p>碰撞、湍流、宏观不稳定性、壁材料、中子、冷却和电网需分域求解，并管理耦合接口与证据。</p></div><img src="/figures/fusion-multiscale-image2.png" alt="Nature风格聚变物理多尺度图版"/><div className="scale"><span>10⁻¹² s<br/><b>碰撞与波</b></span><span>10⁻⁶—10⁻³ s<br/><b>湍流与 MHD</b></span><span>秒—小时<br/><b>放电与热循环</b></span><span>年—十年<br/><b>寿命与经济性</b></span></div></section>
  <section className="figureAtlas"><div className="sectionHead"><p className="eyebrow">02 / 图解整体理念</p><h2>模型如何组合</h2><p>图示为数量级与接口关系；性能以装置和求解器验证为准。</p></div><div className="scienceGrid"><figure><DecisionTimescaleChart/><figcaption><b>A · 决策时间尺度</b>　拖动或悬停查看从控制到整厂优化的模型窗口。</figcaption></figure><figure><FidelityLatencyChart/><figcaption><b>B · 多保真组合</b>　双对数坐标展示求解时间与有效状态维数。</figcaption></figure><figure><CouplingMatrixChart/><figcaption><b>C · 物理接口矩阵</b>　行 → 列表示信息方向；矩阵不要求对称，等级 2 表示通常需要迭代处理的强反馈。</figcaption></figure><figure><img src="/figures/physics-stack-nature.png" alt="聚变物理栈和数字线程"/><figcaption><b>H · 物理栈与数字线程</b>　统一配置、接口和证据，保留各域求解器。</figcaption></figure></div></section>
  <section id="catalog" className="catalog"><div className="sectionHead"><p className="eyebrow">03 / 可筛选技术雷达</p><h2>代码与工具目录</h2><p>开源不等于适合关键决策。卡片列出验证、计算复杂度、实时性与装置证据。</p></div><div className="filters"><input aria-label="搜索工具" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索代码、装置、技术栈或目标…"/><select aria-label="选择物理域" value={domain} onChange={e=>setDomain(e.target.value)}>{domains.map(d=><option key={d}>{d}</option>)}</select><span>{filtered.length} / {tools.length}</span></div><div className="cards">{filtered.map((t,i)=><article className="card" key={t.name}><div className="cardTop"><span>{String(i+1).padStart(2,'0')}</span><a href={t.url} target="_blank" rel="noreferrer">↗</a></div><h3>{t.name}</h3><p className="domain">{t.domain}</p><p>{t.scope}</p><dl><div><dt>开放性</dt><dd>{t.access}</dd></div><div><dt>保真/实时</dt><dd>{t.fidelity} · {t.realtime}</dd></div><div><dt>技术栈</dt><dd>{t.stack}</dd></div><div><dt>验证</dt><dd>{t.validation}</dd></div><div><dt>装置</dt><dd>{t.devices}</dd></div></dl></article>)}</div></section>
  <section className="loop"><div><p className="eyebrow">04 / 可信运行闭环</p><h2>用实验持续校准模型适用域</h2><p>高保真模型解释与外推，快速模型估计与控制，诊断检验预测，工程模型回传热、应力、氚与寿命约束。各环节共享版本化数据本体与验证记录。</p></div><img src="/figures/experiment-model-control-nature.png" alt="Nature风格实验模型控制证据闭环图"/></section>
  <section className="architecture"><div className="sectionHead"><p className="eyebrow">05 / 架构与可信度</p><h2>DINA / MEQ 扩展架构</h2></div><div className="scienceGrid"><figure><img src="/figures/dina-meq-architecture-nature.png" alt="DINA MEQ演进架构"/><figcaption><b>E · 演进架构</b>　保留装置资产包和权威求解器，以数据与证据层连接在线模型和离线证据工厂。</figcaption></figure><figure><img src="/figures/credibility-ladder-nature.png" alt="模型可信度证据梯"/><figcaption><b>F · G0—G5 证据梯</b>　“能运行”不等于“可影响指定决策”；模型影响越大，验证门越严格。</figcaption></figure></div></section>
  <section id="integrated" className="integrated"><div className="sectionHead"><p className="eyebrow">06 / 集成模拟专题</p><h2>集成模拟与运行闭环</h2><p>比较数据、脉冲、全装置、整厂与工业孪生平台。0—3/0—4 分为公开材料支持的规划评分，依据见报告第 11A 章。</p></div><div className="scienceGrid integratedFigures"><figure className="integratedDataFigure"><FrameworkLandscapeChart/><figcaption><b>I · 框架版图</b>　生命周期范围与耦合深度。</figcaption></figure><figure className="integratedDataFigure"><FrameworkCapabilityChart/><figcaption><b>J · 能力矩阵</b>　悬停核对框架—能力单元。</figcaption></figure><figure><img src="/figures/integrated-to-digital-twin-gap-nature.png" alt="集成模拟到数字孪生差距"/><figcaption><b>L · 关键差距</b>　状态同步、在线可信、闭环权限和生命周期连续性。</figcaption></figure><figure><img src="/figures/integrated-twin-reference-architecture-nature.png" alt="集成模拟数字孪生双速架构"/><figcaption><b>M · 双速架构</b>　在线运行环与离线证据工厂通过统一配置和模型发布连接。</figcaption></figure></div><div className="gapBand"><div className="gapChartCell"><MaturityGapChart/></div><div><h3>运行能力缺口</h3><p>集成模拟仍需补齐状态同步、最坏时延、超域检测、安全回退、资产配置与持续 V&amp;V。橙色菱形为目标，虚线 3.0 为运行支持门。</p><a href="/fusion-physics-simulation-report.pdf">阅读第 11A 章完整分析 →</a></div></div><div className="frameworkGroups">{integratedGroups.map(g=><article key={g.group}><header><span>{String(integratedGroups.indexOf(g)+1).padStart(2,'0')}</span><div><h3>{g.group}</h3><p>{g.purpose}</p></div></header>{g.items.map(f=><details key={f.name}><summary><b>{f.name}</b><span>{f.role}</span></summary><div className="frameworkDetail"><p><strong>优势</strong>{f.strengths}</p><p><strong>限制</strong>{f.limits}</p><p><strong>孪生差距</strong>{f.twinGap}</p><a href={f.url} target="_blank" rel="noreferrer">官方/原始来源 ↗</a></div></details>)}</article>)}</div></section>
  <section id="roadmap" className="roadmap"><div className="sectionHead"><p className="eyebrow">07 / 能力门驱动路线</p><h2>从 DINA / MEQ 起步</h2><p>每阶段交付可验证的决策能力。</p></div><PhysicsRoadmapChart/><div className="stages">{physicsRoadmapStages.map(stage=><article key={stage.id}><span>{stage.id}</span><h3>{stage.title}</h3><b>{stage.period}</b><p>{stage.detail}</p></article>)}</div></section>
  <section className="originals"><div className="sectionHead"><p className="eyebrow">08 / 原始研究证据</p><h2>原始研究与模型边界</h2></div><div className="figureGrid"><figure><img src="/figures/original-digital-framework-fig1.png" alt="聚变电厂集成数字框架原论文图"/><figcaption>Patterson 等：聚变电厂集成数字框架。来源：Royal Society Open Science，CC BY 4.0。</figcaption></figure><figure><img src="/figures/original-fuse-architecture-fig1.png" alt="FUSE架构原论文图"/><figcaption>FUSE 的 IMAS 数据本体与多保真工作流。来源：FUSE 预印本。</figcaption></figure><figure><img src="/figures/original-dream-validation-fig5-6.png" alt="DREAM验证原论文图"/><figcaption>DREAM 与解析/独立代码的验证比较。来源：CPC 论文预印本。</figcaption></figure><figure><img src="/figures/original-jorek-starwall-fig2.png" alt="JOREK STARWALL耦合原论文图"/><figcaption>JOREK–STARWALL 真空与壁耦合。来源：JOREK 综述预印本。</figcaption></figure></div></section>
  <section id="evidence" className="evidence"><div className="sectionHead"><p className="eyebrow">09 / 可追溯来源</p><h2>核心文献与官方资源</h2><p>代码、论文、许可与证据等级详见完整报告和本地文献清单。</p></div><div className="refs">{references.map(r=><a key={r.id} href={r.url} target="_blank" rel="noreferrer"><span>{r.id}</span><h3>{r.title}</h3><p>{r.org} · {r.year}</p></a>)}</div></section>
  <SiteFooter />
 </main>
}
