'use client';
import { useMemo, useState } from 'react';
import { domains, references, tools } from '../data';
import { integratedGroups } from '../integrated-data';
import SiteFooter from '../components/SiteFooter';
import SiteNav from '../components/SiteNav';
import {
  CouplingMatrixChart,
  DecisionTimescaleChart,
  FidelityLatencyChart,
  FrameworkCapabilityChart,
  FrameworkLandscapeChart,
  MaturityGapChart,
  PhysicsRoadmapChart,
  physicsRoadmapStages,
} from './PhysicsCharts';
import '../integrated.css';
import './physics.css';

export default function Home(){
 const [query,setQuery]=useState(''); const [domain,setDomain]=useState('全部');
 const filtered=useMemo(()=>tools.filter(t=>(domain==='全部'||t.domain===domain)&&(`${t.name} ${t.scope} ${t.devices} ${t.stack}`.toLowerCase().includes(query.toLowerCase()))),[query,domain]);
 return <main className="physicsPage">
  <SiteNav active="physics" />
  <header id="top" className="hero"><div className="heroCopy"><p className="eyebrow">聚变数字孪生 · 物理模拟技术底座</p><h1>从等离子体控制，走向<br/><em>聚变电厂级可信预测</em></h1><p className="lede">面向非聚变专业的决策者与系统工程师：用一张可追溯的物理地图连接 DINA、MEQ、输运、MHD、边界、中子学、氚与整厂系统模型。</p><div className="actions"><a className="primary" href="/fusion-physics-simulation-report.pdf">下载物理报告</a><a href="/engineering">进入工程仿真分页</a><a href="#catalog">浏览 {tools.length} 项工具</a></div><div className="stats"><span><b>14</b> 类物理域</span><span><b>{tools.length}</b> 项代码/平台</span><span><b>2026-08</b> 证据截止</span></div></div><img src="/figures/fusion-plant-cutaway-image2.png" alt="托卡马克聚变电厂剖面科学示意图"/></header>
  <section className="thesis"><p>关键判断</p><h2>聚变数字孪生不是一个“万能大模型”，而是一套围绕具体决策、按时间尺度编排的模型组合。</h2><div className="three"><article><b>控制闭环</b><p>毫秒到秒；重建、状态估计、执行器响应和风险预测必须确定、可降级、可审计。</p></article><article><b>设计闭环</b><p>小时到月；高保真物理与工程模型提供约束、训练数据和不确定度，而非直接进入实时回路。</p></article><article><b>证据闭环</b><p>每个预测携带版本、输入、适用域、验证层级和置信区间，才能用于工程与安全决策。</p></article></div></section>
  <section id="map" className="map"><div className="sectionHead"><p className="eyebrow">01 / 从微观到电网</p><h2>一台聚变电厂跨越约二十个数量级</h2><p>碰撞、湍流、宏观不稳定性、壁材料、中子、冷却回路和电网不会被同一种数值方法同时高效求解。系统架构的核心是分解、耦合与证据管理。</p></div><img src="/figures/fusion-multiscale-image2.png" alt="Nature风格聚变物理多尺度图版"/><div className="scale"><span>10⁻¹² s<br/><b>碰撞与波</b></span><span>10⁻⁶—10⁻³ s<br/><b>湍流与 MHD</b></span><span>秒—小时<br/><b>放电与热循环</b></span><span>年—十年<br/><b>寿命与经济性</b></span></div></section>
  <section className="figureAtlas"><div className="sectionHead"><p className="eyebrow">02 / 图解整体理念</p><h2>模型组合由决策、反馈和证据共同定义</h2><p>图中区间与位置用于理解数量级和接口关系，具体性能以装置与求解器验证结果为准。</p></div><div className="scienceGrid"><figure><DecisionTimescaleChart/><figcaption><b>A · 决策时间尺度</b>　拖动或悬停查看从控制到整厂优化的模型窗口。</figcaption></figure><figure><FidelityLatencyChart/><figcaption><b>B · 多保真组合</b>　双对数坐标展示求解时间与有效状态维数。</figcaption></figure><figure><CouplingMatrixChart/><figcaption><b>C · 物理接口矩阵</b>　行 → 列表示信息方向；矩阵不要求对称，等级 2 表示通常需要迭代处理的强反馈。</figcaption></figure><figure><img src="/figures/physics-stack-nature.png" alt="聚变物理栈和数字线程"/><figcaption><b>H · 物理栈与数字线程</b>　统一配置、接口和证据，保留各域求解器。</figcaption></figure></div></section>
  <section id="catalog" className="catalog"><div className="sectionHead"><p className="eyebrow">03 / 可筛选技术雷达</p><h2>代码与工具目录</h2><p>“开源”只表示可取得源代码，不等于已经适合关键决策。每张卡片同时保留验证方式、计算复杂度、实时性和装置证据。</p></div><div className="filters"><input aria-label="搜索工具" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索代码、装置、技术栈或目标…"/><select aria-label="选择物理域" value={domain} onChange={e=>setDomain(e.target.value)}>{domains.map(d=><option key={d}>{d}</option>)}</select><span>{filtered.length} / {tools.length}</span></div><div className="cards">{filtered.map((t,i)=><article className="card" key={t.name}><div className="cardTop"><span>{String(i+1).padStart(2,'0')}</span><a href={t.url} target="_blank" rel="noreferrer">↗</a></div><h3>{t.name}</h3><p className="domain">{t.domain}</p><p>{t.scope}</p><dl><div><dt>开放性</dt><dd>{t.access}</dd></div><div><dt>保真/实时</dt><dd>{t.fidelity} · {t.realtime}</dd></div><div><dt>技术栈</dt><dd>{t.stack}</dd></div><div><dt>验证</dt><dd>{t.validation}</dd></div><div><dt>装置</dt><dd>{t.devices}</dd></div></dl></article>)}</div></section>
  <section className="loop"><div><p className="eyebrow">04 / 可信运行闭环</p><h2>实验不是模型的“最后一步”，而是持续校准模型适用域的主线。</h2><p>高保真代码解释与外推；快速模型估计与控制；诊断数据负责证伪；工程模型把热、应力、氚和寿命约束返回给场景设计。所有环节共用版本化数据本体与验证账本。</p></div><img src="/figures/experiment-model-control-nature.png" alt="Nature风格实验模型控制证据闭环图"/></section>
  <section className="architecture"><div className="sectionHead"><p className="eyebrow">05 / 架构与可信度</p><h2>DINA / MEQ 如何扩展，而不失去可审计性</h2></div><div className="scienceGrid"><figure><img src="/figures/dina-meq-architecture-nature.png" alt="DINA MEQ演进架构"/><figcaption><b>E · 演进架构</b>　保留装置资产包和权威求解器，以数据与证据层连接在线模型和离线证据工厂。</figcaption></figure><figure><img src="/figures/credibility-ladder-nature.png" alt="模型可信度证据梯"/><figcaption><b>F · G0—G5 证据梯</b>　“能运行”不等于“可影响指定决策”；模型影响越大，验证门越严格。</figcaption></figure></div></section>
  <section id="integrated" className="integrated"><div className="sectionHead"><p className="eyebrow">06 / 集成模拟专题</p><h2>集成模拟是数字孪生的模型工厂，但还不是运行闭环</h2><p>比较数据平台、脉冲模拟、全装置高保真、整厂设计和工业孪生平台；0—3/0—4 分均为基于公开材料的规划评分，详细依据见完整报告第 11A 章。</p></div><div className="scienceGrid integratedFigures"><figure className="integratedDataFigure"><FrameworkLandscapeChart/><figcaption><b>I · 框架版图</b>　生命周期范围与耦合深度。</figcaption></figure><figure className="integratedDataFigure"><FrameworkCapabilityChart/><figcaption><b>J · 能力矩阵</b>　悬停核对框架—能力单元。</figcaption></figure><figure><img src="/figures/integrated-to-digital-twin-gap-nature.png" alt="集成模拟到数字孪生差距"/><figcaption><b>L · 关键差距</b>　状态同步、在线可信、闭环权限和生命周期连续性。</figcaption></figure><figure><img src="/figures/integrated-twin-reference-architecture-nature.png" alt="集成模拟数字孪生双速架构"/><figcaption><b>M · 双速架构</b>　在线运行环与离线证据工厂通过统一配置和模型发布连接。</figcaption></figure></div><div className="gapBand"><div className="gapChartCell"><MaturityGapChart/></div><div><h3>最需要投资的不是更多求解器</h3><p>典型集成模拟已经能覆盖多物理、统一部分数据并复现实验，但在在线状态同步、最坏时延、超域检测、安全回退、资产配置和持续 V&amp;V 上仍有显著差距。橙色菱形为目标，虚线 3.0 为运行支持门。</p><a href="/fusion-physics-simulation-report.pdf">阅读第 11A 章完整分析 →</a></div></div><div className="frameworkGroups">{integratedGroups.map(g=><article key={g.group}><header><span>{String(integratedGroups.indexOf(g)+1).padStart(2,'0')}</span><div><h3>{g.group}</h3><p>{g.purpose}</p></div></header>{g.items.map(f=><details key={f.name}><summary><b>{f.name}</b><span>{f.role}</span></summary><div className="frameworkDetail"><p><strong>优势</strong>{f.strengths}</p><p><strong>限制</strong>{f.limits}</p><p><strong>孪生差距</strong>{f.twinGap}</p><a href={f.url} target="_blank" rel="noreferrer">官方/原始来源 ↗</a></div></details>)}</article>)}</div></section>
  <section id="roadmap" className="roadmap"><div className="sectionHead"><p className="eyebrow">07 / 能力门驱动路线</p><h2>DINA / MEQ 只是正确的起点</h2><p>每一阶段都以可验证的“决策能力”作为交付，而不是以接入更多代码作为完成标志。</p></div><PhysicsRoadmapChart/><div className="stages">{physicsRoadmapStages.map(stage=><article key={stage.id}><span>{stage.id}</span><h3>{stage.title}</h3><b>{stage.period}</b><p>{stage.detail}</p></article>)}</div></section>
  <section className="originals"><div className="sectionHead"><p className="eyebrow">08 / 原始研究证据</p><h2>从论文图回到模型边界</h2></div><div className="figureGrid"><figure><img src="/figures/original-digital-framework-fig1.png" alt="聚变电厂集成数字框架原论文图"/><figcaption>Patterson 等：聚变电厂集成数字框架。来源：Royal Society Open Science，CC BY 4.0。</figcaption></figure><figure><img src="/figures/original-fuse-architecture-fig1.png" alt="FUSE架构原论文图"/><figcaption>FUSE 的 IMAS 数据本体与多保真工作流。来源：FUSE 预印本。</figcaption></figure><figure><img src="/figures/original-dream-validation-fig5-6.png" alt="DREAM验证原论文图"/><figcaption>DREAM 与解析/独立代码的验证比较。来源：CPC 论文预印本。</figcaption></figure><figure><img src="/figures/original-jorek-starwall-fig2.png" alt="JOREK STARWALL耦合原论文图"/><figcaption>JOREK–STARWALL 真空与壁耦合。来源：JOREK 综述预印本。</figcaption></figure></div></section>
  <section id="evidence" className="evidence"><div className="sectionHead"><p className="eyebrow">09 / 可追溯来源</p><h2>核心文献与官方资源</h2><p>本页只显示核心入口；完整报告和本地文献清单包含更细的代码、论文、许可与证据等级。</p></div><div className="refs">{references.map(r=><a key={r.id} href={r.url} target="_blank" rel="noreferrer"><span>{r.id}</span><h3>{r.title}</h3><p>{r.org} · {r.year}</p></a>)}</div></section>
  <SiteFooter />
 </main>
}
