// Generated by scripts/iter/integrate_iter_high_bundle.mjs after all 18
// immutable release assets pass review. An empty contract fails closed.
export const ITER_HIGH_DETAIL_RELEASE_ASSETS = [
  { partId: "cryostat-base", sha256: "f4daa0cabe2cdc3fb44057d57c5b5863c295015b2d692ea34f86cc7a96a9a34e", bytes: 2003108 },
  { partId: "cryostat-lower", sha256: "e48fcc0d23ba738df3a3184e16a927b86cba93ccdab762112773dffcff1141f4", bytes: 20330804 },
  { partId: "cryostat-top", sha256: "fbd22be80dd003f6810755e425423c037fb6db4083af5a4ae200e82bf0cd8ce3", bytes: 807836 },
  { partId: "cryostat-upper", sha256: "f7b326788c41df1e9f61c96e035b8788b22ec044503c8d0c16a4ab3e68c7e7f9", bytes: 18802744 },
  { partId: "cs", sha256: "d1a8a1b30b9da86cd5d428012c3ce599fb16eca0b4778da3507bd26ceba78cdb", bytes: 6331312 },
  { partId: "divertor", sha256: "54bff21eff660cecd961415af61ce9df4a5319bb941559e390805a675176c278", bytes: 1804300 },
  { partId: "pf1", sha256: "4d802390f02288c13638afc02e1d14d97530abb5fcc872c0a24371cbdaace558", bytes: 400840 },
  { partId: "pf2", sha256: "74c2387b2951c19a51b547b6cd6bccc837c926041319f6d994ef747ffba27d89", bytes: 3598620 },
  { partId: "pf3", sha256: "9c2a34664d2f18c5d91fb499348424401d8637889d7ff4e70a6444fadecccb27", bytes: 1059116 },
  { partId: "pf4", sha256: "7152b2d6eb2c40fbe219fd6db905a6a2cef18604bf8338cf55fe932c8e86d424", bytes: 1858988 },
  { partId: "pf5", sha256: "5a4d67c2644cfb3353f28aab772c19d0c19d525f0829bfee4d66d2fa10bb8c2d", bytes: 707344 },
  { partId: "pf6", sha256: "81c6fbba0bd99cab6b861995bcbbdca8feea7c9cca4a64da645a8201a0f6eeec", bytes: 839244 },
  { partId: "tf-a", sha256: "ca14bb03eac8ac74edcd6861c39c78c80a11bcbbb0f5f12a7cf75f19c3e4222f", bytes: 439032 },
  { partId: "tf-b", sha256: "219e07618fc984e5f6e15f6092c59387cc614beaf273f4a88c73bca2f14ef0a2", bytes: 605324 },
  { partId: "vv1", sha256: "dfbc4da888f415a62bed27c1dda45700cd191f9d8652f5ddcb28c591c59f5503", bytes: 7979988 },
  { partId: "vv2", sha256: "397d0424f70525335d3d167bce13308dac70d8d6a66ee173b350c05cfadfe5b4", bytes: 7908704 },
  { partId: "vv3", sha256: "730d0b8df6ca92bef654f5dcf777f37de3065cfbc45cfc0f5ae74753002cc2a2", bytes: 8686100 },
  { partId: "vv4", sha256: "c3719d8d84ba66ec35d3bff6ba656ccb576d680b353f78feea432d169a08ba53", bytes: 8068908 },
] as const;
