import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { gzipSync } from 'node:zlib';
import path from 'node:path';
import { parseInnerHistory, type DiagnosticsBundle } from '../../app/simulations/diagnostics.ts';
const dir = process.argv[2]; if (!dir) throw new Error('Provide successful stationary run directory');
const hash = (b: Uint8Array) => createHash('sha256').update(b).digest('hex');
const mb = await readFile(path.join(dir, 'run-manifest.json')), m = JSON.parse(mb.toString());
const status = JSON.parse(await readFile(path.join(dir, 'status.json'), 'utf8'));
const raw = await readFile(path.join(dir, 'inner-history.json')), rows = parseInnerHistory(JSON.parse(raw.toString()));
const records = JSON.parse(await readFile('app/simulations/data/fuse-demo.json', 'utf8'));
if (status.state !== 'succeeded' || status.id !== m.runId || m.schema !== 'fuse-native-run.v2' || m.recipe !== 'diiid-default-stationary' || m.execution !== 'succeeded' || !records.some((r: { id: string; source: { recordSha256: string } }) => r.id === m.runId && r.source.recordSha256 === hash(mb)) || !m.artifacts.some((a: { name: string; sha256: string }) => a.name === 'inner-history.json' && a.sha256 === hash(raw)) || rows.length !== m.stationaryHistory.length || rows.at(-1)!.selectedResidual !== m.selectedResidual) throw new Error('Diagnostic evidence mismatch');
const zipped = gzipSync(raw, { level: 9 });
const bundle: DiagnosticsBundle = { runId: m.runId, recordSha256: hash(mb), iterations: rows.length, path: `/data/simulations/${hash(zipped)}.json.gz`, sha256: hash(zipped), bytes: zipped.length, rawSha256: hash(raw), rawBytes: raw.length };
const indexPath = 'app/simulations/data/diagnostics-bundles.json', bundles: DiagnosticsBundle[] = JSON.parse(await readFile(indexPath, 'utf8'));
if (bundles.some(b => b.runId === m.runId)) throw new Error('Already published');
await writeFile(`public${bundle.path}`, zipped, { flag: 'wx' });
await writeFile(indexPath, JSON.stringify([bundle, ...bundles], null, 2) + '\n');
console.log(JSON.stringify({ runId: m.runId, iterations: rows.length, evaluations: rows.map(r => r.evaluationResiduals.length), bytes: zipped.length }));
